-- ============================================================================
--  04_geography.sql — the 58 wilayas of Algeria and their communes
--  Source: github.com/othmanus/algeria-cities (ONS administrative listing)
--  Generated from src/data/algeria.ts. Idempotent.
-- ============================================================================

insert into public.wilayas (code, name, name_ar) values
  ('01', 'Adrar', 'أدرار'),
  ('02', 'Chlef', ' الشلف'),
  ('03', 'Laghouat', 'الأغواط'),
  ('04', 'Oum El Bouaghi', 'أم البواقي'),
  ('05', 'Batna', 'باتنة'),
  ('06', 'Béjaïa', ' بجاية'),
  ('07', 'Biskra', 'بسكرة'),
  ('08', 'Béchar', 'بشار'),
  ('09', 'Blida', 'البليدة'),
  ('10', 'Bouira', 'البويرة'),
  ('11', 'Tamanrasset', 'تمنراست'),
  ('12', 'Tébessa', 'تبسة'),
  ('13', 'Tlemcen', 'تلمسان'),
  ('14', 'Tiaret', 'تيارت'),
  ('15', 'Tizi Ouzou', 'تيزي وزو'),
  ('16', 'Alger', 'الجزائر'),
  ('17', 'Djelfa', 'الجلفة'),
  ('18', 'Jijel', 'جيجل'),
  ('19', 'Sétif', 'سطيف'),
  ('20', 'Saïda', 'سعيدة'),
  ('21', 'Skikda', 'سكيكدة'),
  ('22', 'Sidi Bel Abbès', 'سيدي بلعباس'),
  ('23', 'Annaba', 'عنابة'),
  ('24', 'Guelma', 'قالمة'),
  ('25', 'Constantine', 'قسنطينة'),
  ('26', 'Médéa', 'المدية'),
  ('27', 'Mostaganem', 'مستغانم'),
  ('28', 'M''Sila', 'المسيلة'),
  ('29', 'Mascara', 'معسكر'),
  ('30', 'Ouargla', 'ورقلة'),
  ('31', 'Oran', 'وهران'),
  ('32', 'El Bayadh', 'البيض'),
  ('33', 'Illizi', 'إليزي'),
  ('34', 'Bordj Bou Arreridj', 'برج بوعريريج'),
  ('35', 'Boumerdès', 'بومرداس'),
  ('36', 'El Tarf', 'الطارف'),
  ('37', 'Tindouf', 'تندوف'),
  ('38', 'Tissemsilt', 'تيسمسيلت'),
  ('39', 'El Oued', 'الوادي'),
  ('40', 'Khenchela', 'خنشلة'),
  ('41', 'Souk Ahras', 'سوق أهراس'),
  ('42', 'Tipaza', 'تيبازة'),
  ('43', 'Mila', 'ميلة'),
  ('44', 'Aïn Defla', 'عين الدفلة'),
  ('45', 'Naâma', 'النعامة'),
  ('46', 'Aïn Témouchent', 'عين تيموشنت'),
  ('47', 'Ghardaïa', 'غرداية'),
  ('48', 'Relizane', 'غليزان'),
  ('49', 'Timimoun', 'تيميمون'),
  ('50', 'Bordj Badji Mokhtar', 'برج باجي مختار'),
  ('51', 'Ouled Djellal', 'أولاد جلال'),
  ('52', 'Béni Abbès', 'بني عباس'),
  ('53', 'In Salah', 'عين صالح'),
  ('54', 'In Guezzam', 'عين قزام'),
  ('55', 'Touggourt', 'تقرت'),
  ('56', 'Djanet', 'جانت'),
  ('57', 'El Meghaier', 'المغير'),
  ('58', 'El Menia', 'المنيعة')
on conflict (code) do update set name = excluded.name, name_ar = excluded.name_ar;

-- 01 Adrar
insert into public.communes (wilaya_code, name, name_ar, daira) values
  ('01', 'Adrar', 'أدرار', 'Adrar'),
  ('01', 'Akabli', 'اقبلي', 'Aoulef'),
  ('01', 'Aoulef', 'أولف', 'Aoulef'),
  ('01', 'Bouda', 'بودة', 'Adrar'),
  ('01', 'Fenoughil', 'فنوغيل', 'Fenoughil'),
  ('01', 'In Zghmir', 'إن زغمير', 'Zaouiat Kounta'),
  ('01', 'Ouled Ahmed Timmi', 'أولاد أحمد تيمي', 'Adrar'),
  ('01', 'Reggane', 'رقان', 'Reggane'),
  ('01', 'Sali', 'سالي', 'Reggane'),
  ('01', 'Sebaa', 'السبع', 'Tsabit'),
  ('01', 'Tamantit', 'تامنطيط', 'Fenoughil'),
  ('01', 'Tamest', 'تامست', 'Fenoughil'),
  ('01', 'Timekten', 'تيمقتن', 'Aoulef'),
  ('01', 'Tit', 'تيت', 'Aoulef'),
  ('01', 'Tsabit', 'تسابيت', 'Tsabit'),
  ('01', 'Zaouiet Kounta', 'زاوية كنتة', 'Zaouiat Kounta')
on conflict (wilaya_code, name) do nothing;

-- 02 Chlef
insert into public.communes (wilaya_code, name, name_ar, daira) values
  ('02', 'Abou El Hassane', 'أبو الحسن', 'Abou El Hassane'),
  ('02', 'Ain Merane', 'عين مران', 'Ain Merane'),
  ('02', 'Benairia', 'بنايرية', 'Zeboudja'),
  ('02', 'Beni  Bouattab', 'بني بوعتاب', 'El Karimia'),
  ('02', 'Beni Haoua', 'بني حواء', 'Beni Haoua'),
  ('02', 'Beni Rached', 'بني راشد', 'Oued Fodda'),
  ('02', 'Boukadir', 'بوقادير', 'Boukadir'),
  ('02', 'Bouzeghaia', 'بوزغاية', 'Zeboudja'),
  ('02', 'Breira', 'بريرة', 'Beni Haoua'),
  ('02', 'Chettia', 'الشطية', 'Ouled Fares'),
  ('02', 'Chlef', 'الشلف', 'Chlef'),
  ('02', 'Dahra', 'الظهرة', 'Taougrit'),
  ('02', 'El Hadjadj', 'الحجاج', 'Ouled Ben Abdelkader'),
  ('02', 'El Karimia', 'الكريمية', 'El Karimia'),
  ('02', 'El Marsa', 'المرسى', 'El Marsa'),
  ('02', 'Harchoun', 'حرشون', 'El Karimia'),
  ('02', 'Herenfa', 'الهرانفة', 'Ain Merane'),
  ('02', 'Labiod Medjadja', 'الأبيض مجاجة', 'Ouled Fares'),
  ('02', 'Moussadek', 'مصدق', 'El Marsa'),
  ('02', 'Oued Fodda', 'وادي الفضة', 'Oued Fodda'),
  ('02', 'Oued Goussine', 'وا��ي قوسين', 'Beni Haoua'),
  ('02', 'Oued Sly', 'وادي سلي', 'Boukadir'),
  ('02', 'Ouled Abbes', 'أولاد عباس', 'Oued Fodda'),
  ('02', 'Ouled Ben Abdelkader', 'أولاد بن عبد القادر', 'Ouled Ben Abdelkader'),
  ('02', 'Ouled Fares', 'أولاد فارس', 'Ouled Fares'),
  ('02', 'Oum Drou', 'أم الدروع', 'Chlef'),
  ('02', 'Sendjas', 'سنجاس', 'Chlef'),
  ('02', 'Sidi Abderrahmane', 'سيدي عبد الرحمن', 'Tenes'),
  ('02', 'Sidi Akkacha', 'سيدي عكاشة', 'Tenes'),
  ('02', 'Sobha', 'الصبحة', 'Boukadir'),
  ('02', 'Tadjena', 'تاجنة', 'Abou El Hassane'),
  ('02', 'Talassa', 'تلعصة', 'Abou El Hassane'),
  ('02', 'Taougrit', 'تاوقريت', 'Taougrit'),
  ('02', 'Tenes', 'تنس', 'Tenes'),
  ('02', 'Zeboudja', 'الزبوجة', 'Zeboudja')
on conflict (wilaya_code, name) do nothing;

-- 03 Laghouat
insert into public.communes (wilaya_code, name, name_ar, daira) values
  ('03', 'Aflou', 'أفلو', 'Aflou'),
  ('03', 'Ain Madhi', 'عين ماضي', 'Ain Madhi'),
  ('03', 'Ain Sidi Ali', 'عين سيدي علي', 'Gueltat Sidi Saad'),
  ('03', 'Benacer Benchohra', 'بن ناصر بن شهرة', 'Ksar El Hirane'),
  ('03', 'Brida', 'بريدة', 'Brida'),
  ('03', 'El Assafia', 'العسافية', 'Sidi Makhlouf'),
  ('03', 'El Beidha', 'البيضاء', 'Gueltat Sidi Saad'),
  ('03', 'El Ghicha', 'الغيشة', 'El Ghicha'),
  ('03', 'El Haouaita', 'الحويطة', 'Ain Madhi'),
  ('03', 'Gueltat Sidi Saad', 'قلتة سيدي سعد', 'Gueltat Sidi Saad'),
  ('03', 'Hadj Mechri', 'الحاج مشري', 'Brida'),
  ('03', 'Hassi Delaa', 'حاسي الدلاعة', 'Hassi R''mel'),
  ('03', 'Hassi R''mel', 'حاسي الرمل', 'Hassi R''mel'),
  ('03', 'Kheneg', 'الخنق', 'Ain Madhi'),
  ('03', 'Ksar El Hirane', 'قصر الحيران', 'Ksar El Hirane'),
  ('03', 'Laghouat', 'الأغواط', 'Laghouat'),
  ('03', 'Oued M''zi', 'وادي مزي', 'Oued Morra'),
  ('03', 'Oued Morra', 'وادي مرة', 'Oued Morra'),
  ('03', 'Sebgag', 'سبقاق', 'Aflou'),
  ('03', 'Sidi Bouzid', 'سيدي بوزيد', 'Aflou'),
  ('03', 'Sidi Makhlouf', 'سيدي مخلوف', 'Sidi Makhlouf'),
  ('03', 'Tadjemout', 'تاجموت', 'Ain Madhi'),
  ('03', 'Tadjrouna', 'تاجرونة', 'Ain Madhi'),
  ('03', 'Taouiala', 'تاويالة', 'Brida')
on conflict (wilaya_code, name) do nothing;

-- 04 Oum El Bouaghi
insert into public.communes (wilaya_code, name, name_ar, daira) values
  ('04', 'Ain Babouche', 'عين ببوش', 'Ain Babouche'),
  ('04', 'Ain Beida', 'عين البيضاء', 'Ain Beida'),
  ('04', 'Ain Diss', 'عين الديس', 'Ain Babouche'),
  ('04', 'Ain Fekroun', 'عين فكرون', 'Ain Fekroun'),
  ('04', 'Ain Kercha', 'عين كرشة', 'Ain Kercha'),
  ('04', 'Ain M''lila', 'عين مليلة', 'Ain M''lila'),
  ('04', 'Ain Zitoun', 'عين الزيتون', 'Oum El Bouaghi'),
  ('04', 'Behir Chergui', 'بحير الشرقي', 'Meskiana'),
  ('04', 'Berriche', 'بريش', 'Ain Beida'),
  ('04', 'Bir Chouhada', 'بئر الشهداء', 'Souk Naamane'),
  ('04', 'Dhalaa', 'الضلعة', 'Dhalaa'),
  ('04', 'El Amiria', 'العامرية', 'Sigus'),
  ('04', 'El Belala', 'البلالة', 'Meskiana'),
  ('04', 'El Djazia', 'الجازية', 'Dhalaa'),
  ('04', 'El Fedjoudj Boughrara Sa', 'الفجوج بوغرارة سعودي', 'Ain Fekroun'),
  ('04', 'El Harmilia', 'الحرملية', 'Ain Kercha'),
  ('04', 'Fkirina', 'فكيرينة', 'F''kirina'),
  ('04', 'Hanchir Toumghani', 'هنشير تومغني', 'Ain Kercha'),
  ('04', 'Ksar Sbahi', 'قصر الصباحي', 'Ksar Sbahi'),
  ('04', 'Meskiana', 'مسكيانة', 'Meskiana'),
  ('04', 'Oued Nini', 'وادي نيني', 'F''kirina'),
  ('04', 'Ouled Gacem', 'أولاد قاسم', 'Ain M''lila'),
  ('04', 'Ouled Hamla', 'أولاد حملة', 'Ain M''lila'),
  ('04', 'Ouled Zouai', 'أولاد زواي', 'Souk Naamane'),
  ('04', 'Oum El Bouaghi', 'أم البواقي', 'Oum El Bouaghi'),
  ('04', 'Rahia', 'الرحية', 'Meskiana'),
  ('04', 'Sigus', 'سيقوس', 'Sigus'),
  ('04', 'Souk Naamane', 'سوق نعمان', 'Souk Naamane'),
  ('04', 'Zorg', 'الزرق', 'Ain Beida')
on conflict (wilaya_code, name) do nothing;

-- 05 Batna
insert into public.communes (wilaya_code, name, name_ar, daira) values
  ('05', 'Ain Djasser', 'عين جاسر', 'Ain Djasser'),
  ('05', 'Ain Touta', 'عين التوتة', 'Ain Touta'),
  ('05', 'Ain Yagout', 'عين ياقوت', 'El Madher'),
  ('05', 'Arris', 'أريس', 'Arris'),
  ('05', 'Azil Abedelkader', 'عزيل عبد القادر', 'Djezzar'),
  ('05', 'Barika', 'بريكة', 'Barika'),
  ('05', 'Batna', 'باتنة', 'Batna'),
  ('05', 'Beni Foudhala El Hakania', 'بني فضالة الحقانية', 'Ain Touta'),
  ('05', 'Bitam', 'بيطام', 'Barika'),
  ('05', 'Boulhilat', 'بولهيلات', 'Chemora'),
  ('05', 'Boumagueur', 'بومقر', 'N''gaous'),
  ('05', 'Boumia', 'بومية', 'El Madher'),
  ('05', 'Bouzina', 'بوزينة', 'Bouzina'),
  ('05', 'Chemora', 'الشمرة', 'Chemora'),
  ('05', 'Chir', 'شير', 'Theniet El Abed'),
  ('05', 'Djerma', 'جرمة', 'El Madher'),
  ('05', 'Djezzar', 'الجزار', 'Djezzar'),
  ('05', 'El Hassi', 'الحاسي', 'Ain Djasser'),
  ('05', 'El Madher', 'المعذر', 'El Madher'),
  ('05', 'Fesdis', 'فسديس', 'Batna'),
  ('05', 'Foum Toub', 'فم الطوب', 'Ichemoul'),
  ('05', 'Ghassira', 'غسيرة', 'Tkout'),
  ('05', 'Gosbat', 'القصبات', 'Ras El Aioun'),
  ('05', 'Guigba', 'القيقبة', 'Ras El Aioun'),
  ('05', 'Hidoussa', 'حيدوسة', 'Merouana'),
  ('05', 'Ichemoul', 'إشمول', 'Ichemoul'),
  ('05', 'Inoughissen', 'إينوغيسن', 'Ichemoul'),
  ('05', 'Kimmel', 'كيمل', 'Tkout'),
  ('05', 'Ksar Bellezma', 'قصر بلزمة', 'Merouana'),
  ('05', 'Larbaa', 'لارباع', 'Bouzina'),
  ('05', 'Lazrou', 'لازرو', 'Seriana'),
  ('05', 'Lemcene', 'لمسان', 'Ouled Si Slimane'),
  ('05', 'M Doukal', 'إمدوكل', 'Barika'),
  ('05', 'Maafa', 'معافة', 'Ain Touta'),
  ('05', 'Menaa', 'منعة', 'Menaa'),
  ('05', 'Merouana', 'مروانة', 'Merouana'),
  ('05', 'N Gaous', 'نقاوس', 'N''gaous'),
  ('05', 'Oued Chaaba', 'وادي الشعبة', 'Batna'),
  ('05', 'Oued El Ma', 'وادي الماء', 'Merouana'),
  ('05', 'Oued Taga', 'وادي الطاقة', 'Theniet El Abed'),
  ('05', 'Ouled Ammar', 'أولاد عمار', 'Djezzar'),
  ('05', 'Ouled Aouf', 'أولاد عوف', 'Ain Touta'),
  ('05', 'Ouled Fadel', 'أولاد فاضل', 'Timgad'),
  ('05', 'Ouled Sellem', 'أولاد سلام', 'Ras El Aioun'),
  ('05', 'Ouled Si Slimane', 'أولاد سي سليمان', 'Ouled Si Slimane'),
  ('05', 'Ouyoun El Assafir', 'عيون العصافير', 'Tazoult'),
  ('05', 'Rahbat', 'الرحبات', 'Ras El Aioun'),
  ('05', 'Ras El Aioun', 'رأس العيون', 'Ras El Aioun'),
  ('05', 'Sefiane', 'سفيان', 'N''gaous'),
  ('05', 'Seggana', 'سقانة', 'Seggana'),
  ('05', 'Seriana', 'سريانة', 'Seriana'),
  ('05', 'T Kout', 'تكوت', 'Tkout'),
  ('05', 'Talkhamt', 'تالخمت', 'Ras El Aioun'),
  ('05', 'Taxlent', 'تاكسلانت', 'Ouled Si Slimane'),
  ('05', 'Tazoult', 'تازولت', 'Tazoult'),
  ('05', 'Teniet El Abed', 'ثنية العابد', 'Theniet El Abed'),
  ('05', 'Tighanimine', 'تيغانمين', 'Arris'),
  ('05', 'Tigharghar', 'تغرغار', 'Menaa'),
  ('05', 'Tilatou', 'تيلاطو', 'Seggana'),
  ('05', 'Timgad', 'تيمقاد', 'Timgad'),
  ('05', 'Zanet El Beida', 'زانة البيضاء', 'Seriana')
on conflict (wilaya_code, name) do nothing;

-- 06 Béjaïa
insert into public.communes (wilaya_code, name, name_ar, daira) values
  ('06', 'Adekar', 'أدكار', 'Adekar'),
  ('06', 'Ait R''zine', 'أيت رزين', 'Ighil Ali'),
  ('06', 'Ait-Smail', 'أيت إسماعيل', 'Darguina'),
  ('06', 'Akbou', 'أقبو', 'Akbou'),
  ('06', 'Akfadou', 'أكفادو', 'Chemini'),
  ('06', 'Amalou', 'أمالو', 'Seddouk'),
  ('06', 'Amizour', 'أميزور', 'Amizour'),
  ('06', 'Aokas', 'أوقاس', 'Aokas'),
  ('06', 'Barbacha', 'برباشة', 'Barbacha'),
  ('06', 'Bejaia', 'بجاية', 'Bejaia'),
  ('06', 'Beni Djellil', 'بني جليل', 'Amizour'),
  ('06', 'Beni K''sila', 'بني كسيلة', 'Adekar'),
  ('06', 'Beni-Mallikeche', 'بني مليكش', 'Tazmalt'),
  ('06', 'Benimaouche', 'بني معوش', 'Beni Maouche'),
  ('06', 'Boudjellil', 'بو جليل', 'Tazmalt'),
  ('06', 'Bouhamza', 'بوحمزة', 'Seddouk'),
  ('06', 'Boukhelifa', 'بوخليفة', 'Tichy'),
  ('06', 'Chellata', 'شلاطة', 'Akbou'),
  ('06', 'Chemini', 'شميني', 'Chemini'),
  ('06', 'Darguina', 'درقينة', 'Darguina'),
  ('06', 'Dra El Caid', 'ذراع القايد', 'Kherrata'),
  ('06', 'El Kseur', 'القصر', 'El Kseur'),
  ('06', 'Fenaia Il Maten', 'فناية الماثن', 'El Kseur'),
  ('06', 'Feraoun', 'فرعون', 'Amizour'),
  ('06', 'Ighil-Ali', 'إغيل علي', 'Ighil Ali'),
  ('06', 'Ighram', 'اغرم', 'Akbou'),
  ('06', 'Kendira', 'كنديرة', 'Barbacha'),
  ('06', 'Kherrata', 'خراطة', 'Kherrata'),
  ('06', 'Leflaye', 'الفلاي', 'Sidi Aich'),
  ('06', 'M''cisna', 'مسيسنة', 'Seddouk'),
  ('06', 'Melbou', 'مالبو', 'Souk El Tenine'),
  ('06', 'Oued Ghir', 'وادي غير', 'Bejaia'),
  ('06', 'Ouzellaguen', 'أوزلاقن', 'Ifri Ouzellaguene'),
  ('06', 'Seddouk', 'صدوق', 'Seddouk'),
  ('06', 'Sidi Ayad', 'سيدي عياد', 'Sidi Aich'),
  ('06', 'Sidi-Aich', 'سيدي عيش', 'Sidi Aich'),
  ('06', 'Smaoun', 'سمعون', 'Amizour'),
  ('06', 'Souk El Tenine', 'سوق لإثنين', 'Souk El Tenine'),
  ('06', 'Souk Oufella', 'سوق اوفلا', 'Chemini'),
  ('06', 'Tala Hamza', 'تالة حمزة', 'Tichy'),
  ('06', 'Tamokra', 'تامقرة', 'Akbou'),
  ('06', 'Tamridjet', 'تامريجت', 'Souk El Tenine'),
  ('06', 'Taourit Ighil', 'تاوريرت إغيل', 'Adekar'),
  ('06', 'Taskriout', 'تاسكريوت', 'Darguina'),
  ('06', 'Tazmalt', 'تازمالت', 'Tazmalt'),
  ('06', 'Tibane', 'طيبان', 'Chemini'),
  ('06', 'Tichy', 'تيشي', 'Tichy'),
  ('06', 'Tifra', 'تيفرة', 'Sidi Aich'),
  ('06', 'Timezrit', 'تيمزريت', 'Timezrit'),
  ('06', 'Tinebdar', 'تينبدار', 'Sidi Aich'),
  ('06', 'Tizi-N''berber', 'تيزي نبربر', 'Aokas'),
  ('06', 'Toudja', 'توجة', 'El Kseur')
on conflict (wilaya_code, name) do nothing;

-- 07 Biskra
insert into public.communes (wilaya_code, name, name_ar, daira) values
  ('07', 'Ain Naga', 'عين الناقة', 'Sidi Okba'),
  ('07', 'Ain Zaatout', 'عين زعطوط', 'El Kantara'),
  ('07', 'Biskra', 'بسكرة', 'Biskra'),
  ('07', 'Bordj Ben Azzouz', 'برج بن عزوز', 'Tolga'),
  ('07', 'Bouchakroun', 'بوشقرون', 'Tolga'),
  ('07', 'Branis', 'برانيس', 'Djemorah'),
  ('07', 'Chetma', 'شتمة', 'Sidi Okba'),
  ('07', 'Djemorah', 'جمورة', 'Djemorah'),
  ('07', 'El Feidh', 'الفيض', 'Zeribet El Oued'),
  ('07', 'El Ghrous', 'الغروس', 'Foughala'),
  ('07', 'El Hadjab', 'الحاجب', 'Biskra'),
  ('07', 'El Haouch', 'الحوش', 'Sidi Okba'),
  ('07', 'El Kantara', 'القنطرة', 'El Kantara'),
  ('07', 'El Outaya', 'الوطاية', 'El Outaya'),
  ('07', 'Foughala', 'فوغالة', 'Foughala'),
  ('07', 'Khenguet Sidi Nadji', 'خنقة سيدي ناجي', 'Zeribet El Oued'),
  ('07', 'Lichana', 'ليشانة', 'Tolga'),
  ('07', 'Lioua', 'ليوة', 'Ourlal'),
  ('07', 'M''chouneche', 'مشونش', 'Mechouneche'),
  ('07', 'M''lili', 'مليلي', 'Ourlal'),
  ('07', 'Mekhadma', 'مخادمة', 'Ourlal'),
  ('07', 'Meziraa', 'المزيرعة', 'Zeribet El Oued'),
  ('07', 'Oumache', 'أوماش', 'Ourlal'),
  ('07', 'Ourlal', 'أورلال', 'Ourlal'),
  ('07', 'Sidi Okba', 'سيدي عقبة', 'Sidi Okba'),
  ('07', 'Tolga', 'طولقة', 'Tolga'),
  ('07', 'Zeribet El Oued', 'زريبة الوادي', 'Zeribet El Oued')
on conflict (wilaya_code, name) do nothing;

-- 08 Béchar
insert into public.communes (wilaya_code, name, name_ar, daira) values
  ('08', 'Abadla', 'العبادلة', 'Abadla'),
  ('08', 'Bechar', 'بشار', 'Bechar'),
  ('08', 'Beni-Ounif', 'بني ونيف', 'Beni Ounif'),
  ('08', 'Boukais', 'بوكايس', 'Lahmar'),
  ('08', 'Erg-Ferradj', 'عرق فراج', 'Abadla'),
  ('08', 'Kenadsa', 'القنادسة', 'Kenadsa'),
  ('08', 'Lahmar', 'لحمر', 'Lahmar'),
  ('08', 'Machraa-Houari-Boumediene', 'مشرع هواري بومدين', 'Abadla'),
  ('08', 'Meridja', 'المريجة', 'Kenadsa'),
  ('08', 'Mogheul', 'موغل', 'Lahmar'),
  ('08', 'Tabelbala', 'تبلبالة', 'Tabelbala'),
  ('08', 'Taghit', 'تاغيت', 'Taghit')
on conflict (wilaya_code, name) do nothing;

-- 09 Blida
insert into public.communes (wilaya_code, name, name_ar, daira) values
  ('09', 'Ain Romana', 'عين الرمانة', 'Mouzaia'),
  ('09', 'Beni Mered', 'بني مراد', 'Ouled Yaich'),
  ('09', 'Beni-Tamou', 'بني تامو', 'Oued El Alleug'),
  ('09', 'Benkhelil', 'بن خليل', 'Oued El Alleug'),
  ('09', 'Blida', 'البليدة', 'Blida'),
  ('09', 'Bouarfa', 'بوعرفة', 'Blida'),
  ('09', 'Boufarik', 'بوفاريك', 'Boufarik'),
  ('09', 'Bougara', 'بوقرة', 'Bougara'),
  ('09', 'Bouinan', 'بوعينان', 'Bouinan'),
  ('09', 'Chebli', 'الشبلي', 'Bouinan'),
  ('09', 'Chiffa', 'الشفة', 'Mouzaia'),
  ('09', 'Chrea', 'الشريعة', 'Ouled Yaich'),
  ('09', 'Djebabra', 'جبابرة', 'Meftah'),
  ('09', 'El-Affroun', 'العفرون', 'El Affroun'),
  ('09', 'Guerrouaou', 'قرواو', 'Boufarik'),
  ('09', 'Hammam Elouane', 'حمام ملوان', 'Bougara'),
  ('09', 'Larbaa', 'الأربعاء', 'Larbaa'),
  ('09', 'Meftah', 'مفتاح', 'Meftah'),
  ('09', 'Mouzaia', 'موزاية', 'Mouzaia'),
  ('09', 'Oued  Djer', 'وادي جر', 'El Affroun'),
  ('09', 'Oued El Alleug', 'وادي العلايق', 'Oued El Alleug'),
  ('09', 'Ouled Slama', 'اولاد سلامة', 'Bougara'),
  ('09', 'Ouled Yaich', 'أولاد يعيش', 'Ouled Yaich'),
  ('09', 'Souhane', 'صوحان', 'Larbaa'),
  ('09', 'Soumaa', 'الصومعة', 'Boufarik')
on conflict (wilaya_code, name) do nothing;

-- 10 Bouira
insert into public.communes (wilaya_code, name, name_ar, daira) values
  ('10', 'Aghbalou', 'أغبالو', 'M''chedallah'),
  ('10', 'Ahl El Ksar', 'أهل القصر', 'Bechloul'),
  ('10', 'Ain El Hadjar', 'عين الحجر', 'Ain Bessem'),
  ('10', 'Ain Laloui', 'عين العلوي', 'Ain Bessem'),
  ('10', 'Ain Turk', 'عين الترك', 'Bouira'),
  ('10', 'Ain-Bessem', 'عين بسام', 'Ain Bessem'),
  ('10', 'Ait Laaziz', 'أيت لعزيز', 'Bouira'),
  ('10', 'Aomar', 'أعمر', 'Kadiria'),
  ('10', 'Ath Mansour', 'آث  منصور', 'M''chedallah'),
  ('10', 'Bechloul', 'بشلول', 'Bechloul'),
  ('10', 'Bir Ghbalou', 'بئر غبالو', 'Bir Ghbalou'),
  ('10', 'Bordj Okhriss', 'برج أوخريص', 'Bordj Okhriss'),
  ('10', 'Bouderbala', 'بودربالة', 'Lakhdaria'),
  ('10', 'Bouira', 'البويرة', 'Bouira'),
  ('10', 'Boukram', '��وكرم', 'Lakhdaria'),
  ('10', 'Chorfa', 'شرفة', 'M''chedallah'),
  ('10', 'Dechmia', 'الدشمية', 'Sour El Ghozlane'),
  ('10', 'Dirah', 'ديرة', 'Sour El Ghozlane'),
  ('10', 'Djebahia', 'جباحية', 'Kadiria'),
  ('10', 'El Adjiba', 'العجيبة', 'Bechloul'),
  ('10', 'El Asnam', 'الأسنام', 'Bechloul'),
  ('10', 'El Hachimia', 'الهاشمية', 'El Hachimia'),
  ('10', 'El Khabouzia', 'الخبوزية', 'Bir Ghbalou'),
  ('10', 'El-Hakimia', 'الحاكمية', 'Sour El Ghozlane'),
  ('10', 'El-Mokrani', 'المقراني', 'Souk El Khemis'),
  ('10', 'Guerrouma', 'قرومة', 'Lakhdaria'),
  ('10', 'Hadjera Zerga', 'الحجرة الزرقاء', 'Bordj Okhriss'),
  ('10', 'Haizer', 'حيزر', 'Haizer'),
  ('10', 'Hanif', 'حنيف', 'M''chedallah'),
  ('10', 'Kadiria', 'قادرية', 'Kadiria'),
  ('10', 'Lakhdaria', 'الأخضرية', 'Lakhdaria'),
  ('10', 'M Chedallah', 'أمشدالة', 'M''chedallah'),
  ('10', 'Maala', 'معلة', 'Lakhdaria'),
  ('10', 'Maamora', 'المعمورة', 'Sour El Ghozlane'),
  ('10', 'Mezdour', 'مزدور', 'Bordj Okhriss'),
  ('10', 'Oued El Berdi', 'وادي البردي', 'El Hachimia'),
  ('10', 'Ouled Rached', 'أولاد راشد', 'Bechloul'),
  ('10', 'Raouraoua', 'روراوة', 'Bir Ghbalou'),
  ('10', 'Ridane', 'ريدان', 'Sour El Ghozlane'),
  ('10', 'Saharidj', 'سحاريج', 'M''chedallah'),
  ('10', 'Souk El Khemis', 'سوق الخميس', 'Souk El Khemis'),
  ('10', 'Sour El Ghozlane', 'سور الغزلان', 'Sour El Ghozlane'),
  ('10', 'Taghzout', 'تاغزوت', 'Haizer'),
  ('10', 'Taguedite', 'تاقديت', 'Bordj Okhriss'),
  ('10', 'Z''barbar (El Isseri )', 'زبربر', 'Lakhdaria')
on conflict (wilaya_code, name) do nothing;

-- 11 Tamanrasset
insert into public.communes (wilaya_code, name, name_ar, daira) values
  ('11', 'Abelsa', 'ابلسة', 'Silet'),
  ('11', 'Ain Amguel', 'عين امقل', 'Tamanrasset'),
  ('11', 'Idles', 'أدلس', 'Tazrouk'),
  ('11', 'Tamanrasset', 'تمنراست', 'Tamanrasset'),
  ('11', 'Tazrouk', 'تاظروك', 'Tazrouk')
on conflict (wilaya_code, name) do nothing;

-- 12 Tébessa
insert into public.communes (wilaya_code, name, name_ar, daira) values
  ('12', 'Ain Zerga', 'عين الزرقاء', 'Ouenza'),
  ('12', 'Bedjene', 'بجن', 'El Ogla'),
  ('12', 'Bekkaria', 'بكارية', 'El Kouif'),
  ('12', 'Bir Dheheb', 'بئر الذهب', 'Morsott'),
  ('12', 'Bir Mokkadem', 'بئر مقدم', 'Bir Mokadem'),
  ('12', 'Bir-El-Ater', 'بئر العاتر', 'Bir El Ater'),
  ('12', 'Boukhadra', 'بوخضرة', 'El Aouinet'),
  ('12', 'Boulhaf Dyr', 'بولحاف الدير', 'El Kouif'),
  ('12', 'Cheria', 'الشريعة', 'Cheria'),
  ('12', 'El Kouif', 'الكويف', 'El Kouif'),
  ('12', 'El Malabiod', 'الماء الابيض', 'El Malabiod'),
  ('12', 'El Meridj', 'المريج', 'Ouenza'),
  ('12', 'El Mezeraa', 'المزرعة', 'El Ogla'),
  ('12', 'El Ogla', 'العقلة', 'El Ogla'),
  ('12', 'El Ogla El Malha', 'العقلة المالحة', 'Bir El Ater'),
  ('12', 'El-Aouinet', 'العوينات', 'El Aouinet'),
  ('12', 'El-Houidjbet', 'الحويجبات', 'El Malabiod'),
  ('12', 'Ferkane', 'فركان', 'Negrine'),
  ('12', 'Guorriguer', 'قريقر', 'Bir Mokadem'),
  ('12', 'Hammamet', 'الحمامات', 'Bir Mokadem'),
  ('12', 'Morsott', 'مرسط', 'Morsott'),
  ('12', 'Negrine', 'نقرين', 'Negrine'),
  ('12', 'Ouenza', 'الونزة', 'Ouenza'),
  ('12', 'Oum Ali', 'أم علي', 'Oum Ali'),
  ('12', 'Saf Saf El Ouesra', 'صفصاف الوسرى', 'Oum Ali'),
  ('12', 'Stah Guentis', 'سطح قنطيس', 'El Ogla'),
  ('12', 'Tebessa', 'تبسة', 'Tebessa'),
  ('12', 'Telidjen', 'ثليجان', 'Cheria')
on conflict (wilaya_code, name) do nothing;

-- 13 Tlemcen
insert into public.communes (wilaya_code, name, name_ar, daira) values
  ('13', 'Ain Fetah', 'عين فتاح', 'Fellaoucene'),
  ('13', 'Ain Fezza', 'عين فزة', 'Chetouane'),
  ('13', 'Ain Ghoraba', 'عين غرابة', 'Mansourah'),
  ('13', 'Ain Kebira', 'عين الكبيرة', 'Fellaoucene'),
  ('13', 'Ain Nehala', 'عين النحالة', 'Ain Tellout'),
  ('13', 'Ain Tellout', 'عين تالوت', 'Ain Tellout'),
  ('13', 'Ain Youcef', 'عين يوسف', 'Remchi'),
  ('13', 'Amieur', 'عمير', 'Chetouane'),
  ('13', 'Azail', 'العزايل', 'Beni Snous'),
  ('13', 'Bab El Assa', 'باب العسة', 'Bab El Assa'),
  ('13', 'Beni Bahdel', 'بني بهدل', 'Beni Snous'),
  ('13', 'Beni Boussaid', 'بني بوسعيد', 'Beni Boussaid'),
  ('13', 'Beni Khellad', 'بني خلاد', 'Honnaine'),
  ('13', 'Beni Mester', 'بني مستر', 'Mansourah'),
  ('13', 'Beni Ouarsous', 'بني وارسوس', 'Remchi'),
  ('13', 'Beni Smiel', 'بني صميل', 'Ouled Mimoun'),
  ('13', 'Beni Snous', 'بني سنوس', 'Beni Snous'),
  ('13', 'Bensekrane', 'بن سكران', 'Bensekrane'),
  ('13', 'Bouhlou', 'بوحلو', 'Sabra'),
  ('13', 'Bouihi', 'البويهي', 'Sidi Djillali'),
  ('13', 'Chetouane', 'شتوان', 'Chetouane'),
  ('13', 'Dar Yaghmoracen', 'دار يغمراسن', 'Ghazaouet'),
  ('13', 'Djebala', 'جبالة', 'Nedroma'),
  ('13', 'El Aricha', 'العريشة', 'Sebdou'),
  ('13', 'El Fehoul', 'الفحول', 'Remchi'),
  ('13', 'El Gor', 'القور', 'Sebdou'),
  ('13', 'Fellaoucene', 'فلاوسن', 'Fellaoucene'),
  ('13', 'Ghazaouet', 'الغزوات', 'Ghazaouet'),
  ('13', 'Hammam Boughrara', 'حمام بوغرارة', 'Maghnia'),
  ('13', 'Hennaya', 'الحناية', 'Hennaya'),
  ('13', 'Honnaine', 'هنين', 'Honnaine'),
  ('13', 'M''sirda Fouaga', 'مسيردة الفواقة', 'Marsa Ben Mehdi'),
  ('13', 'Maghnia', 'مغنية', 'Maghnia'),
  ('13', 'Mansourah', 'منصورة', 'Mansourah'),
  ('13', 'Marsa Ben M''hidi', 'مرسى بن مهيدي', 'Marsa Ben Mehdi'),
  ('13', 'Nedroma', 'ندرومة', 'Nedroma'),
  ('13', 'Oued Lakhdar', 'وادي الخضر', 'Ouled Mimoun'),
  ('13', 'Ouled Mimoun', 'أولاد ميمون', 'Ouled Mimoun'),
  ('13', 'Ouled Riyah', 'أولاد رياح', 'Hennaya'),
  ('13', 'Remchi', 'الرمشي', 'Remchi'),
  ('13', 'Sabra', 'صبرة', 'Sabra'),
  ('13', 'Sebbaa Chioukh', 'سبعة شيوخ', 'Remchi'),
  ('13', 'Sebdou', 'سبدو', 'Sebdou'),
  ('13', 'Sidi Abdelli', 'سيدي العبدلي', 'Bensekrane'),
  ('13', 'Sidi Djillali', 'سيدي الجيلالي', 'Sidi Djillali'),
  ('13', 'Sidi Medjahed', 'سيدي مجاهد', 'Beni Boussaid'),
  ('13', 'Souahlia', 'السواحلية', 'Ghazaouet'),
  ('13', 'Souani', 'السواني', 'Bab El Assa'),
  ('13', 'Souk Tleta', 'سوق الثلاثاء', 'Bab El Assa'),
  ('13', 'Terny Beni Hediel', 'تيرني بني هديل', 'Mansourah'),
  ('13', 'Tianet', 'تيانت', 'Ghazaouet'),
  ('13', 'Tlemcen', 'تلمسان', 'Tlemcen'),
  ('13', 'Zenata', 'زناتة', 'Hennaya')
on conflict (wilaya_code, name) do nothing;

-- 14 Tiaret
insert into public.communes (wilaya_code, name, name_ar, daira) values
  ('14', 'Ain Bouchekif', 'عين بوشقيف', 'Dahmouni'),
  ('14', 'Ain Deheb', 'عين الذهب', 'Ain Deheb'),
  ('14', 'Ain Dzarit', 'عين دزاريت', 'Mahdia'),
  ('14', 'Ain El Hadid', 'عين الحديد', 'Frenda'),
  ('14', 'Ain Kermes', 'عين كرمس', 'Ain Kermes'),
  ('14', 'Bougara', 'بوقرة', 'Hamadia'),
  ('14', 'Chehaima', 'شحيمة', 'Ain Deheb'),
  ('14', 'Dahmouni', 'دحموني', 'Dahmouni'),
  ('14', 'Djebilet Rosfa', 'جبيلات الرصفاء', 'Ain Kermes'),
  ('14', 'Djillali Ben Amar', 'جيلالي بن عمار', 'Mechraa Sfa'),
  ('14', 'Faidja', 'الفايجة', 'Sougueur'),
  ('14', 'Frenda', 'فرندة', 'Frenda'),
  ('14', 'Guertoufa', 'قرطوفة', 'Rahouia'),
  ('14', 'Hamadia', 'حمادية', 'Hamadia'),
  ('14', 'Ksar Chellala', 'قصر الشلالة', 'Ksar Chellala'),
  ('14', 'Madna', 'مادنة', 'Ain Kermes'),
  ('14', 'Mahdia', 'مهدية', 'Mahdia'),
  ('14', 'Mechraa Safa', 'مشرع الصفا', 'Mechraa Sfa'),
  ('14', 'Medrissa', 'مدريسة', 'Ain Kermes'),
  ('14', 'Medroussa', 'مدروسة', 'Medroussa'),
  ('14', 'Meghila', 'مغيلة', 'Meghila'),
  ('14', 'Mellakou', 'ملاكو', 'Medroussa'),
  ('14', 'Nadorah', 'الناظورة', 'Mahdia'),
  ('14', 'Naima', 'النعيمة', 'Ain Deheb'),
  ('14', 'Oued Lilli', 'وادي ليلي', 'Oued Lili'),
  ('14', 'Rahouia', 'الرحوية', 'Rahouia'),
  ('14', 'Rechaiga', 'الرشايقة', 'Hamadia'),
  ('14', 'Sebaine', 'السبعين', 'Mahdia'),
  ('14', 'Sebt', 'السبت', 'Meghila'),
  ('14', 'Serghine', 'سرغين', 'Ksar Chellala'),
  ('14', 'Si Abdelghani', 'سي عبد الغني', 'Sougueur'),
  ('14', 'Sidi Abderrahmane', 'سيدي عبد الرحمن', 'Ain Kermes'),
  ('14', 'Sidi Ali Mellal', 'سيدي علي ملال', 'Oued Lili'),
  ('14', 'Sidi Bakhti', 'سيدي بختي', 'Medroussa'),
  ('14', 'Sidi Hosni', 'سيدي حسني', 'Meghila'),
  ('14', 'Sougueur', 'السوقر', 'Sougueur'),
  ('14', 'Tagdempt', 'تاقدمت', 'Mechraa Sfa'),
  ('14', 'Takhemaret', 'تخمرت', 'Frenda'),
  ('14', 'Tiaret', 'تيارت', 'Tiaret'),
  ('14', 'Tidda', 'تيدة', 'Oued Lili'),
  ('14', 'Tousnina', 'توسنينة', 'Sougueur'),
  ('14', 'Zmalet El Emir Abdelkade', 'زمالة  الأمير عبد القادر', 'Ksar Chellala')
on conflict (wilaya_code, name) do nothing;

-- 15 Tizi Ouzou
insert into public.communes (wilaya_code, name, name_ar, daira) values
  ('15', 'Abi-Youcef', 'أبي يوسف', 'Ain El Hammam'),
  ('15', 'Aghribs', 'أغريب', 'Azeffoun'),
  ('15', 'Agouni-Gueghrane', 'أقني قغران', 'Ouadhias'),
  ('15', 'Ain-El-Hammam', 'عين الحمام', 'Ain El Hammam'),
  ('15', 'Ain-Zaouia', 'عين الزاوية', 'Draa El Mizan'),
  ('15', 'Ait Aggouacha', 'أيت عقـواشة', 'Larbaa Nath Iraten'),
  ('15', 'Ait Bouaddou', 'أيت بــوادو', 'Ouadhias'),
  ('15', 'Ait Boumahdi', 'أيت بومهدي', 'Ouacif'),
  ('15', 'Ait Khellili', 'أيت خليلي', 'Mekla'),
  ('15', 'Ait Yahia Moussa', 'أيت يحي موسى', 'Draa El Mizan'),
  ('15', 'Ait-Aissa-Mimoun', 'أيت عيسى ميمون', 'Ouaguenoun'),
  ('15', 'Ait-Chafaa', 'أيت شافع', 'Azeffoun'),
  ('15', 'Ait-Mahmoud', 'أيت محمود', 'Beni Douala'),
  ('15', 'Ait-Oumalou', 'أيت  أومالو', 'Tizi Rached'),
  ('15', 'Ait-Toudert', 'أيت تودرت', 'Ouacif'),
  ('15', 'Ait-Yahia', 'أيت يحيى', 'Ain El Hammam'),
  ('15', 'Akbil', 'اقبيل', 'Ain El Hammam'),
  ('15', 'Akerrou', 'أقرو', 'Azeffoun'),
  ('15', 'Assi-Youcef', 'أسي يوسف', 'Boghni'),
  ('15', 'Azazga', 'عزازقة', 'Azazga'),
  ('15', 'Azeffoun', 'أزفون', 'Azeffoun'),
  ('15', 'Beni Zmenzer', 'بنــــي زمنزار', 'Beni Douala'),
  ('15', 'Beni-Aissi', 'بني عيسي', 'Beni Douala'),
  ('15', 'Beni-Douala', 'بني دوالة', 'Beni Douala'),
  ('15', 'Beni-Yenni', 'بني يني', 'Benni Yenni'),
  ('15', 'Beni-Zikki', 'بني زيكــي', 'Bouzeguene'),
  ('15', 'Boghni', 'بوغني', 'Boghni'),
  ('15', 'Boudjima', 'بوجيمة', 'Makouda'),
  ('15', 'Bounouh', 'بونوح', 'Boghni'),
  ('15', 'Bouzeguene', 'بوزقــن', 'Bouzeguene'),
  ('15', 'Draa-Ben-Khedda', 'ذراع بن خدة', 'Draa Ben Khedda'),
  ('15', 'Draa-El-Mizan', 'ذراع الميزان', 'Draa El Mizan'),
  ('15', 'Freha', 'فريحة', 'Azazga'),
  ('15', 'Frikat', 'فريقات', 'Draa El Mizan'),
  ('15', 'Iboudrarene', 'إبودرارن', 'Benni Yenni'),
  ('15', 'Idjeur', 'إيجــار', 'Bouzeguene'),
  ('15', 'Iferhounene', 'إفــرحــونان', 'Iferhounene'),
  ('15', 'Ifigha', 'إيفيغاء', 'Azazga'),
  ('15', 'Iflissen', 'إفليـــسن', 'Tigzirt'),
  ('15', 'Illilten', 'إيلـيــلتـن', 'Iferhounene'),
  ('15', 'Illoula Oumalou', 'إيلولة أومـــالو', 'Bouzeguene'),
  ('15', 'Imsouhal', 'إمســوحال', 'Iferhounene'),
  ('15', 'Irdjen', 'إيرجـــن', 'Larbaa Nath Iraten'),
  ('15', 'Larbaa Nath Irathen', 'الأربعــاء ناث إيراثن', 'Larbaa Nath Iraten'),
  ('15', 'M''kira', 'مكيرة', 'Tizi-Ghenif'),
  ('15', 'Maatkas', 'معـــاتقة', 'Maatkas'),
  ('15', 'Makouda', 'ماكودة', 'Makouda'),
  ('15', 'Mechtras', 'مشطراس', 'Boghni'),
  ('15', 'Mekla', 'مقــلع', 'Mekla'),
  ('15', 'Mizrana', 'ميزرانـــة', 'Tigzirt'),
  ('15', 'Ouacif', 'واسيف', 'Ouacif'),
  ('15', 'Ouadhias', 'واضية', 'Ouadhias'),
  ('15', 'Ouaguenoun', 'واقنون', 'Ouaguenoun'),
  ('15', 'Sidi Namane', 'سيدي نعمان', 'Draa Ben Khedda'),
  ('15', 'Souama', 'صوامـــع', 'Mekla'),
  ('15', 'Souk-El-Tenine', 'سوق الإثنين', 'Maatkas'),
  ('15', 'Tadmait', 'تادمايت', 'Draa Ben Khedda'),
  ('15', 'Tigzirt', 'تيقـزيرت', 'Tigzirt'),
  ('15', 'Timizart', 'تيمـيزار', 'Ouaguenoun'),
  ('15', 'Tirmitine', 'تيرمتين', 'Draa Ben Khedda'),
  ('15', 'Tizi N''tleta', 'تيزي نثلاثة', 'Ouadhias'),
  ('15', 'Tizi-Gheniff', 'تيزي غنيف', 'Tizi-Ghenif'),
  ('15', 'Tizi-Ouzou', 'تيزي وزو', 'Tizi Ouzou'),
  ('15', 'Tizi-Rached', 'تيزي راشد', 'Tizi Rached'),
  ('15', 'Yakourene', 'إعــكورن', 'Azazga'),
  ('15', 'Yatafene', 'يطــافن', 'Benni Yenni'),
  ('15', 'Zekri', 'زكري', 'Azazga')
on conflict (wilaya_code, name) do nothing;

-- 16 Alger
insert into public.communes (wilaya_code, name, name_ar, daira) values
  ('16', 'Ain Benian', 'عين بنيان', 'Cheraga'),
  ('16', 'Ain Taya', 'عين طاية', 'Dar El Beida'),
  ('16', 'Alger Centre', 'الجزائر الوسطى', 'Sidi M''hamed'),
  ('16', 'Bab El Oued', 'باب الوادي', 'Bab El Oued'),
  ('16', 'Bab Ezzouar', 'باب الزوار', 'Dar El Beida'),
  ('16', 'Baba Hassen', 'بابا حسن', 'Draria'),
  ('16', 'Bachedjerah', 'باش جراح', 'El Harrach'),
  ('16', 'Baraki', 'براقي', 'Baraki'),
  ('16', 'Ben Aknoun', 'ابن عكنون', 'Bouzareah'),
  ('16', 'Beni Messous', 'بني مسوس', 'Bouzareah'),
  ('16', 'Bir Mourad Rais', 'بئر مراد رايس', 'Bir Mourad Rais'),
  ('16', 'Bir Touta', 'بئر توتة', 'Birtouta'),
  ('16', 'Birkhadem', 'بئر خادم', 'Bir Mourad Rais'),
  ('16', 'Bologhine Ibnou Ziri', 'بولوغين بن زيري', 'Bab El Oued'),
  ('16', 'Bordj El Bahri', 'برج البحري', 'Dar El Beida'),
  ('16', 'Bordj El Kiffan', 'برج الكيفان', 'Dar El Beida'),
  ('16', 'Bourouba', 'بوروبة', 'El Harrach'),
  ('16', 'Bouzareah', 'بوزريعة', 'Bouzareah'),
  ('16', 'Casbah', 'القصبة', 'Bab El Oued'),
  ('16', 'Cheraga', 'الشراقة', 'Cheraga'),
  ('16', 'Dar El Beida', 'الدار البيضاء', 'Dar El Beida'),
  ('16', 'Dely Ibrahim', 'دالي ابراهيم', 'Cheraga'),
  ('16', 'Djasr Kasentina', 'جسر قسنطينة', 'Bir Mourad Rais'),
  ('16', 'Douira', 'الدويرة', 'Draria'),
  ('16', 'Draria', 'الدرارية', 'Draria'),
  ('16', 'El Achour', 'العاشور', 'Draria'),
  ('16', 'El Biar', 'الابيار', 'Bouzareah'),
  ('16', 'El Harrach', 'الحراش', 'El Harrach'),
  ('16', 'El Madania', 'المدنية', 'Sidi M''hamed'),
  ('16', 'El Magharia', 'المغارية', 'Hussein Dey'),
  ('16', 'El Marsa', 'المرسى', 'Dar El Beida'),
  ('16', 'El Mouradia', 'المرادية', 'Sidi M''hamed'),
  ('16', 'Hammamet', 'الحمامات', 'Cheraga'),
  ('16', 'Herraoua', 'هراوة', 'Rouiba'),
  ('16', 'Hussein Dey', 'حسين داي', 'Hussein Dey'),
  ('16', 'Hydra', 'حيدرة', 'Bir Mourad Rais'),
  ('16', 'Khraissia', 'الخرايسية', 'Draria'),
  ('16', 'Kouba', 'القبة', 'Hussein Dey'),
  ('16', 'Les Eucalyptus', 'الكاليتوس', 'Baraki'),
  ('16', 'Maalma', 'المعالمة', 'Zeralda'),
  ('16', 'Mohamed Belouzdad', 'محمد بلوزداد', 'Hussein Dey'),
  ('16', 'Mohammadia', 'المحمدية', 'Dar El Beida'),
  ('16', 'Oued Koriche', 'وادي قريش', 'Bab El Oued'),
  ('16', 'Oued Smar', 'وادي السمار', 'El Harrach'),
  ('16', 'Ouled Chebel', 'اولاد شبل', 'Birtouta'),
  ('16', 'Ouled Fayet', 'اولاد فايت', 'Cheraga'),
  ('16', 'Rahmania', 'الرحمانية', 'Zeralda'),
  ('16', 'Rais Hamidou', 'الرايس حميدو', 'Bab El Oued'),
  ('16', 'Reghaia', 'رغاية', 'Rouiba'),
  ('16', 'Rouiba', 'الرويبة', 'Rouiba'),
  ('16', 'Sehaoula', 'السحاولة', 'Bir Mourad Rais'),
  ('16', 'Sidi M''hamed', 'سيدي امحمد', 'Sidi M''hamed'),
  ('16', 'Sidi Moussa', 'سيدي موسى', 'Baraki'),
  ('16', 'Souidania', 'سويدانية', 'Zeralda'),
  ('16', 'Staoueli', 'سطاوالي', 'Zeralda'),
  ('16', 'Tessala El Merdja', 'تسالة المرجة', 'Birtouta'),
  ('16', 'Zeralda', 'زرالدة', 'Zeralda')
on conflict (wilaya_code, name) do nothing;

-- 17 Djelfa
insert into public.communes (wilaya_code, name, name_ar, daira) values
  ('17', 'Ain Chouhada', 'عين الشهداء', 'El Idrissia'),
  ('17', 'Ain El Ibel', 'عين الإبل', 'Ain El Ibel'),
  ('17', 'Ain Fekka', 'عين فقه', 'Had Sahary'),
  ('17', 'Ain Maabed', 'عين معبد', 'Hassi Bahbah'),
  ('17', 'Ain Oussera', 'عين وسارة', 'Ain Oussera'),
  ('17', 'Amourah', 'عمورة', 'Faidh El Botma'),
  ('17', 'Benhar', 'بنهار', 'Birine'),
  ('17', 'Benyagoub', 'بن يعقوب', 'Charef'),
  ('17', 'Birine', 'بيرين', 'Birine'),
  ('17', 'Bouira Lahdab', 'بويرة الأحداب', 'Had Sahary'),
  ('17', 'Charef', 'الشارف', 'Charef'),
  ('17', 'Dar Chioukh', 'دار الشيوخ', 'Dar Chioukh'),
  ('17', 'Deldoul', 'دلدول', 'Messaad'),
  ('17', 'Djelfa', 'الجلفة', 'Djelfa'),
  ('17', 'Douis', 'دويس', 'El Idrissia'),
  ('17', 'El Guedid', 'القديد', 'Charef'),
  ('17', 'El Idrissia', 'الادريسية', 'El Idrissia'),
  ('17', 'El Khemis', 'الخميس', 'Sidi Laadjel'),
  ('17', 'Faidh El Botma', 'فيض البطمة', 'Faidh El Botma'),
  ('17', 'Guernini', 'قرنيني', 'Ain Oussera'),
  ('17', 'Guettara', 'قطارة', 'Messaad'),
  ('17', 'Had Sahary', 'حد الصحاري', 'Had Sahary'),
  ('17', 'Hassi Bahbah', 'حاسي بحبح', 'Hassi Bahbah'),
  ('17', 'Hassi El Euch', 'حاسي العش', 'Hassi Bahbah'),
  ('17', 'Hassi Fedoul', 'حاسي فدول', 'Sidi Laadjel'),
  ('17', 'M''liliha', 'مليليحة', 'Dar Chioukh'),
  ('17', 'Messaad', 'مسعد', 'Messaad'),
  ('17', 'Moudjebara', 'مجبارة', 'Ain El Ibel'),
  ('17', 'Oum Laadham', 'أم العظام', 'Faidh El Botma'),
  ('17', 'Sed Rahal', 'سد الرحال', 'Messaad'),
  ('17', 'Selmana', 'سلمانة', 'Messaad'),
  ('17', 'Sidi Baizid', 'سيدي بايزيد', 'Dar Chioukh'),
  ('17', 'Sidi Laadjel', 'سيدي لعجال', 'Sidi Laadjel'),
  ('17', 'Taadmit', 'تعظميت', 'Ain El Ibel'),
  ('17', 'Zaafrane', 'زعفران', 'Hassi Bahbah'),
  ('17', 'Zaccar', 'زكار', 'Ain El Ibel')
on conflict (wilaya_code, name) do nothing;

-- 18 Jijel
insert into public.communes (wilaya_code, name, name_ar, daira) values
  ('18', 'Bordj T''har', 'برج الطهر', 'Chekfa'),
  ('18', 'Boudria Beniyadjis', 'بودريعة بني  ياجيس', 'Djimla'),
  ('18', 'Bouraoui Belhadef', 'بوراوي بلهادف', 'El Ancer'),
  ('18', 'Boussif Ouled Askeur', 'بوسيف أولاد عسكر', 'Taher'),
  ('18', 'Chahna', 'الشحنة', 'Taher'),
  ('18', 'Chekfa', 'الشقفة', 'Chekfa'),
  ('18', 'Djemaa Beni Habibi', 'الجمعة بني حبيبي', 'El Ancer'),
  ('18', 'Djimla', 'جيملة', 'Djimla'),
  ('18', 'El Ancer', 'العنصر', 'El Ancer'),
  ('18', 'El Aouana', 'العوانة', 'El Aouana'),
  ('18', 'El Kennar Nouchfi', 'القنار نشفي', 'Chekfa'),
  ('18', 'El Milia', 'الميلية', 'El Milia'),
  ('18', 'Emir Abdelkader', 'الامير عبد القادر', 'Taher'),
  ('18', 'Erraguene Souissi', 'أراقن سويسي', 'Ziamah Mansouriah'),
  ('18', 'Ghebala', 'غبالة', 'Settara'),
  ('18', 'Jijel', 'جيجل', 'Jijel'),
  ('18', 'Kaous', 'قاوس', 'Texenna'),
  ('18', 'Khiri Oued Adjoul', 'خيري واد عجول', 'El Ancer'),
  ('18', 'Oudjana', 'وجانة', 'Taher'),
  ('18', 'Ouled Rabah', 'أولاد رابح', 'Sidi Marouf'),
  ('18', 'Ouled Yahia Khadrouch', 'أولاد يحيى خدروش', 'El Milia'),
  ('18', 'Selma Benziada', 'سلمى بن زيادة', 'El Aouana'),
  ('18', 'Settara', 'السطارة', 'Settara'),
  ('18', 'Sidi Abdelaziz', 'سيدي عبد العزيز', 'Chekfa'),
  ('18', 'Sidi Marouf', 'سيدي معروف', 'Sidi Marouf'),
  ('18', 'Taher', 'الطاهير', 'Taher'),
  ('18', 'Texenna', 'تاكسنة', 'Texenna'),
  ('18', 'Ziama Mansouriah', 'زيامة منصورية', 'Ziamah Mansouriah')
on conflict (wilaya_code, name) do nothing;

-- 19 Sétif
insert into public.communes (wilaya_code, name, name_ar, daira) values
  ('19', 'Ain Abessa', 'عين عباسة', 'Ain Arnat'),
  ('19', 'Ain Arnat', 'عين أرنات', 'Ain Arnat'),
  ('19', 'Ain Azel', 'عين أزال', 'Ain Azel'),
  ('19', 'Ain El Kebira', 'عين الكبيرة', 'Ain El Kebira'),
  ('19', 'Ain Lahdjar', 'عين الحجر', 'Ain Azel'),
  ('19', 'Ain Oulmene', 'عين ولمان', 'Ain Oulmene'),
  ('19', 'Ain-Legradj', 'عين لقراج', 'Beni Ourtilane'),
  ('19', 'Ain-Roua', 'عين الروى', 'Bougaa'),
  ('19', 'Ain-Sebt', 'عين السبت', 'Beni Aziz'),
  ('19', 'Ait Naoual Mezada', 'أيت نوال مزادة', 'Bouandas'),
  ('19', 'Ait-Tizi', 'ايت تيزي', 'Bouandas'),
  ('19', 'Amoucha', 'عموشة', 'Amoucha'),
  ('19', 'Babor', 'بابور', 'Babor'),
  ('19', 'Bazer-Sakra', 'بازر سكرة', 'El Eulma'),
  ('19', 'Beidha Bordj', 'بيضاء برج', 'Ain Azel'),
  ('19', 'Bellaa', 'بلاعة', 'Bir El Arch'),
  ('19', 'Beni Chebana', 'بني شبانة', 'Beni Ourtilane'),
  ('19', 'Beni Fouda', 'بني فودة', 'Djemila'),
  ('19', 'Beni Ourtilane', 'بني ورتيلان', 'Beni Ourtilane'),
  ('19', 'Beni Oussine', 'بني وسين', 'Bougaa'),
  ('19', 'Beni-Aziz', 'بني عزيز', 'Beni Aziz'),
  ('19', 'Beni-Mouhli', 'بني موحلي', 'Beni Ourtilane'),
  ('19', 'Bir Haddada', 'بئر حدادة', 'Ain Azel'),
  ('19', 'Bir-El-Arch', 'بئر العرش', 'Bir El Arch'),
  ('19', 'Bouandas', 'بوعنداس', 'Bouandas'),
  ('19', 'Bougaa', 'بوقاعة', 'Bougaa'),
  ('19', 'Bousselam', 'بوسلام', 'Bouandas'),
  ('19', 'Boutaleb', 'بوطالب', 'Salah Bey'),
  ('19', 'Dehamcha', 'الدهامشة', 'Ain El Kebira'),
  ('19', 'Djemila', 'جميلة', 'Djemila'),
  ('19', 'Draa-Kebila', 'ذراع قبيلة', 'Hammam Guergour'),
  ('19', 'El Eulma', 'العلمة', 'El Eulma'),
  ('19', 'El Ouricia', 'أوريسيا', 'Ain Arnat'),
  ('19', 'El-Ouldja', 'الولجة', 'Bir El Arch'),
  ('19', 'Guellal', 'قلال', 'Ain Oulmene'),
  ('19', 'Guelta Zerka', 'قلتة زرقاء', 'El Eulma'),
  ('19', 'Guenzet', 'قنزات', 'Guenzet'),
  ('19', 'Guidjel', 'قجال', 'Guidjel'),
  ('19', 'Hamam Soukhna', 'حمام السخنة', 'Hammam Sokhna'),
  ('19', 'Hamma', 'الحامة', 'Salah Bey'),
  ('19', 'Hammam Guergour', 'حمام قرقور', 'Hammam Guergour'),
  ('19', 'Harbil', 'حربيل', 'Guenzet'),
  ('19', 'Kasr El Abtal', 'قصر الابطال', 'Ain Oulmene'),
  ('19', 'Maaouia', 'معاوية', 'Beni Aziz'),
  ('19', 'Maouaklane', 'ماوكلان', 'Maoklane'),
  ('19', 'Mezloug', 'مزلوق', 'Ain Arnat'),
  ('19', 'Oued El Bared', 'واد البارد', 'Amoucha'),
  ('19', 'Ouled Addouane', 'أولاد عدوان', 'Ain El Kebira'),
  ('19', 'Ouled Sabor', 'أولاد صابر', 'Guidjel'),
  ('19', 'Ouled Si Ahmed', 'أولاد سي أحمد', 'Ain Oulmene'),
  ('19', 'Ouled Tebben', 'أولاد تبان', 'Salah Bey'),
  ('19', 'Rosfa', 'الرصفة', 'Salah Bey'),
  ('19', 'Salah Bey', 'صالح باي', 'Salah Bey'),
  ('19', 'Serdj-El-Ghoul', 'سرج الغول', 'Babor'),
  ('19', 'Setif', 'سطيف', 'Setif'),
  ('19', 'Tachouda', 'تاشودة', 'Bir El Arch'),
  ('19', 'Tala-Ifacene', 'تالة إيفاسن', 'Maoklane'),
  ('19', 'Taya', 'الطاية', 'Hammam Sokhna'),
  ('19', 'Tella', 'التلة', 'Hammam Sokhna'),
  ('19', 'Tizi N''bechar', 'تيزي نبشار', 'Amoucha')
on conflict (wilaya_code, name) do nothing;

-- 20 Saïda
insert into public.communes (wilaya_code, name, name_ar, daira) values
  ('20', 'Ain El Hadjar', 'عين الحجر', 'Ain El Hadjar'),
  ('20', 'Ain Sekhouna', 'عين السخونة', 'El Hassasna'),
  ('20', 'Ain Soltane', 'عين السلطان', 'Ouled Brahim'),
  ('20', 'Doui Thabet', 'دوي ثابت', 'Youb'),
  ('20', 'El Hassasna', 'الحساسنة', 'El Hassasna'),
  ('20', 'Hounet', 'هونت', 'Sidi Boubekeur'),
  ('20', 'Maamora', 'المعمورة', 'El Hassasna'),
  ('20', 'Moulay Larbi', 'مولاي العربي', 'Ain El Hadjar'),
  ('20', 'Ouled Brahim', 'أولاد إبراهيم', 'Ouled Brahim'),
  ('20', 'Ouled Khaled', 'أولاد خالد', 'Sidi Boubekeur'),
  ('20', 'Saida', 'سعيدة', 'Saida'),
  ('20', 'Sidi Ahmed', 'سيدي احمد', 'Ain El Hadjar'),
  ('20', 'Sidi Amar', 'سيدي عمر', 'Sidi Boubekeur'),
  ('20', 'Sidi Boubekeur', 'سيدي بوبكر', 'Sidi Boubekeur'),
  ('20', 'Tircine', 'تيرسين', 'Ouled Brahim'),
  ('20', 'Youb', 'يوب', 'Youb')
on conflict (wilaya_code, name) do nothing;

-- 21 Skikda
insert into public.communes (wilaya_code, name, name_ar, daira) values
  ('21', 'Ain Bouziane', 'عين بوزيان', 'Sidi Mezghiche'),
  ('21', 'Ain Charchar', 'عين شرشار', 'Azzaba'),
  ('21', 'Ain Kechra', 'عين قشرة', 'Ain Kechra'),
  ('21', 'Ain Zouit', 'عين زويت', 'El Hadaiek'),
  ('21', 'Azzaba', 'عزابة', 'Azzaba'),
  ('21', 'Bekkouche Lakhdar', 'بكوش لخضر', 'Ben Azzouz'),
  ('21', 'Ben Azzouz', 'بن عزوز', 'Ben Azzouz'),
  ('21', 'Beni Bechir', 'بني بشير', 'Ramdane Djamel'),
  ('21', 'Beni Oulbane', 'بني ولبان', 'Sidi Mezghiche'),
  ('21', 'Beni Zid', 'بني زيد', 'Collo'),
  ('21', 'Bin El Ouiden', 'بين الويدان', 'Tamalous'),
  ('21', 'Bouchetata', 'بوشطاطة', 'El Hadaiek'),
  ('21', 'Cheraia', 'الشرايع', 'Collo'),
  ('21', 'Collo', 'القل', 'Collo'),
  ('21', 'Djendel Saadi Mohamed', 'جندل سعدي محمد', 'Azzaba'),
  ('21', 'El Arrouch', 'الحروش', 'El Harrouch'),
  ('21', 'El Ghedir', 'الغدير', 'Azzaba'),
  ('21', 'El Hadaiek', 'الحدائق', 'El Hadaiek'),
  ('21', 'El Marsa', 'المرسى', 'Ben Azzouz'),
  ('21', 'Emjez Edchich', 'مجاز الدشيش', 'El Harrouch'),
  ('21', 'Es Sebt', 'السبت', 'Azzaba'),
  ('21', 'Filfila', 'فلفلة', 'Skikda'),
  ('21', 'Hammadi Krouma', 'حمادي كرومة', 'Skikda'),
  ('21', 'Kanoua', 'قنواع', 'Zitouna'),
  ('21', 'Kerkara', 'الكركرة', 'Tamalous'),
  ('21', 'Khenag Maoune', 'خناق مايو', 'Ouled Attia'),
  ('21', 'Oued Zhour', 'وادي الزهور', 'Ouled Attia'),
  ('21', 'Ouldja Boulbalout', 'الولجة بولبلوط', 'Ain Kechra'),
  ('21', 'Ouled Attia', 'أولاد عطية', 'Ouled Attia'),
  ('21', 'Ouled Habbaba', 'أولاد حبابة', 'El Harrouch'),
  ('21', 'Oum Toub', 'أم الطوب', 'Oum Toub'),
  ('21', 'Ramdane Djamel', 'رمضان جمال', 'Ramdane Djamel'),
  ('21', 'Salah Bouchaour', 'صالح بو الشعور', 'El Harrouch'),
  ('21', 'Sidi Mezghiche', 'سيدي مزغيش', 'Sidi Mezghiche'),
  ('21', 'Skikda', 'سكيكدة', 'Skikda'),
  ('21', 'Tamalous', 'تمالوس', 'Tamalous'),
  ('21', 'Zerdezas', 'زردازة', 'El Harrouch'),
  ('21', 'Zitouna', 'الزيتونة', 'Zitouna')
on conflict (wilaya_code, name) do nothing;

-- 22 Sidi Bel Abbès
insert into public.communes (wilaya_code, name, name_ar, daira) values
  ('22', 'Ain El Berd', 'عين البرد', 'Ain El Berd'),
  ('22', 'Ain Kada', 'عين قادة', 'Sidi Ali Boussidi'),
  ('22', 'Ain Thrid', 'عين الثريد', 'Tessala'),
  ('22', 'Ain Tindamine', 'عين تندمين', 'Moulay Slissen'),
  ('22', 'Ain- Adden', 'عين أدن', 'Sfisef'),
  ('22', 'Amarnas', 'العمارنة', 'Sidi Lahcene'),
  ('22', 'Bedrabine El Mokrani', 'بضرابين المقراني', 'Ben Badis'),
  ('22', 'Belarbi', 'بلعربي', 'Mostefa  Ben Brahim'),
  ('22', 'Ben Badis', 'بن باديس', 'Ben Badis'),
  ('22', 'Benachiba Chelia', 'بن عشيبة شلية', 'Tenira'),
  ('22', 'Bir El Hammam', 'بئر الحمام', 'Marhoum'),
  ('22', 'Boudjebaa El Bordj', 'بوجبهة البرج', 'Sfisef'),
  ('22', 'Boukhanefis', 'بوخنفيس', 'Sidi Ali Ben Youb'),
  ('22', 'Chetouane Belaila', 'شيطوان البلايلة', 'Ben Badis'),
  ('22', 'Dhaya', 'الضاية', 'Telagh'),
  ('22', 'El Hacaiba', 'الحصيبة', 'Moulay Slissen'),
  ('22', 'Hassi Dahou', 'حاسي دحو', 'Tenira'),
  ('22', 'Hassi Zahana', 'حاسي زهانة', 'Ben Badis'),
  ('22', 'Lamtar', 'لمطار', 'Sidi Ali Boussidi'),
  ('22', 'M''cid', 'مسيد', 'Sfisef'),
  ('22', 'Makedra', 'مكدرة', 'Ain El Berd'),
  ('22', 'Marhoum', 'مرحوم', 'Marhoum'),
  ('22', 'Merine', 'مرين', 'Merine'),
  ('22', 'Mezaourou', 'مزاورو', 'Telagh'),
  ('22', 'Mostefa  Ben Brahim', 'مصطفى بن ابراهيم', 'Mostefa  Ben Brahim'),
  ('22', 'Moulay Slissen', 'مولاي سليسن', 'Moulay Slissen'),
  ('22', 'Oued Sebaa', 'وادي السبع', 'Ras El Ma'),
  ('22', 'Oued Sefioun', 'وادي سفيون', 'Tenira'),
  ('22', 'Oued Taourira', 'وادي تاوريرة', 'Merine'),
  ('22', 'Ras El Ma', 'راس الماء', 'Ras El Ma'),
  ('22', 'Redjem Demouche', 'رجم دموش', 'Ras El Ma'),
  ('22', 'Sehala Thaoura', 'السهالة الثورة', 'Tessala'),
  ('22', 'Sfisef', 'سفيزف', 'Sfisef'),
  ('22', 'Sidi Ali Benyoub', 'سيدي علي بن يوب', 'Sidi Ali Ben Youb'),
  ('22', 'Sidi Ali Boussidi', 'سيدي علي بوسيدي', 'Sidi Ali Boussidi'),
  ('22', 'Sidi Bel-Abbes', 'سيدي بلعباس', 'Sidi Bel Abbes'),
  ('22', 'Sidi Brahim', 'سيدي ابراهيم', 'Ain El Berd'),
  ('22', 'Sidi Chaib', 'سيدي شعيب', 'Marhoum'),
  ('22', 'Sidi Dahou Zairs', 'سيدي دحو الزاير', 'Sidi Ali Boussidi'),
  ('22', 'Sidi Hamadouche', 'سيدي حمادوش', 'Ain El Berd'),
  ('22', 'Sidi Khaled', 'سيدي خالد', 'Sidi Lahcene'),
  ('22', 'Sidi Lahcene', 'سيدي لحسن', 'Sidi Lahcene'),
  ('22', 'Sidi Yacoub', 'سيدي يعقوب', 'Sidi Lahcene'),
  ('22', 'Tabia', 'طابية', 'Sidi Ali Ben Youb'),
  ('22', 'Taoudmout', 'تاودموت', 'Merine'),
  ('22', 'Tefessour', 'تفسور', 'Merine'),
  ('22', 'Teghalimet', 'تغاليمت', 'Telagh'),
  ('22', 'Telagh', 'تلاغ', 'Telagh'),
  ('22', 'Tenira', 'تنيرة', 'Tenira'),
  ('22', 'Tessala', 'تسالة', 'Tessala'),
  ('22', 'Tilmouni', 'تلموني', 'Mostefa  Ben Brahim'),
  ('22', 'Zerouala', 'زروا��ة', 'Mostefa  Ben Brahim')
on conflict (wilaya_code, name) do nothing;

-- 23 Annaba
insert into public.communes (wilaya_code, name, name_ar, daira) values
  ('23', 'Ain El Berda', 'عين الباردة', 'Ain El Berda'),
  ('23', 'Annaba', 'عنابة', 'Annaba'),
  ('23', 'Berrahal', 'برحال', 'Berrahal'),
  ('23', 'Chetaibi', 'شطايبي', 'Chetaibi'),
  ('23', 'Cheurfa', 'الشرفة', 'Ain El Berda'),
  ('23', 'El Bouni', 'البوني', 'El Bouni'),
  ('23', 'El Eulma', 'العلمة', 'Ain El Berda'),
  ('23', 'El Hadjar', 'الحجار', 'El Hadjar'),
  ('23', 'Oued El Aneb', 'واد العنب', 'Berrahal'),
  ('23', 'Seraidi', 'سرايدي', 'Annaba'),
  ('23', 'Sidi Amar', 'سيدي عمار', 'El Hadjar'),
  ('23', 'Treat', 'التريعات', 'Berrahal')
on conflict (wilaya_code, name) do nothing;

-- 24 Guelma
insert into public.communes (wilaya_code, name, name_ar, daira) values
  ('24', 'Ain Ben Beida', 'عين بن بيضاء', 'Bouchegouf'),
  ('24', 'Ain Larbi', 'عين العربي', 'Ain Makhlouf'),
  ('24', 'Ain Makhlouf', 'عين مخلوف', 'Ain Makhlouf'),
  ('24', 'Ain Regada', 'عين رقادة', 'Oued Zenati'),
  ('24', 'Ain Sandel', 'عين صندل', 'Khezaras'),
  ('24', 'Belkheir', 'بلخير', 'Guelaat Bousbaa'),
  ('24', 'Bendjarah', 'بن جراح', 'Guelma'),
  ('24', 'Beni Mezline', 'بني مزلين', 'Guelaat Bousbaa'),
  ('24', 'Bordj Sabath', 'برج صباط', 'Oued Zenati'),
  ('24', 'Bou Hachana', 'بوحشانة', 'Khezaras'),
  ('24', 'Bou Hamdane', 'بوحمدان', 'Hammam Debagh'),
  ('24', 'Bouati Mahmoud', 'بوعاتي محمود', 'Heliopolis'),
  ('24', 'Bouchegouf', 'بوشقوف', 'Bouchegouf'),
  ('24', 'Boumahra Ahmed', 'بومهرة أحمد', 'Guelaat Bousbaa'),
  ('24', 'Dahouara', 'الدهوارة', 'Hammam N''bails'),
  ('24', 'Djeballah Khemissi', 'جبالة الخميسي', 'Guelaat Bousbaa'),
  ('24', 'El Fedjoudj', 'الفجوج', 'Heliopolis'),
  ('24', 'Guelaat Bou Sbaa', 'قلعة بوصبع', 'Guelaat Bousbaa'),
  ('24', 'Guelma', 'قالمة', 'Guelma'),
  ('24', 'Hammam Debagh', 'حمام دباغ', 'Hammam Debagh'),
  ('24', 'Hammam N''bail', 'حمام النبايل', 'Hammam N''bails'),
  ('24', 'Heliopolis', 'هيليوبوليس', 'Heliopolis'),
  ('24', 'Houari Boumedienne', 'هواري بومدين', 'Ain Hessainia'),
  ('24', 'Khezaras', 'لخزارة', 'Khezaras'),
  ('24', 'Medjez Amar', 'مجاز عمار', 'Ain Hessainia'),
  ('24', 'Medjez Sfa', 'مجاز الصفاء', 'Bouchegouf'),
  ('24', 'Nechmaya', 'نشماية', 'Guelaat Bousbaa'),
  ('24', 'Oued Cheham', 'وادي الشحم', 'Hammam N''bails'),
  ('24', 'Oued Ferragha', 'وادي فراغة', 'Bouchegouf'),
  ('24', 'Oued Zenati', 'وادي الزناتي', 'Oued Zenati'),
  ('24', 'Ras El Agba', 'رأس العقبة', 'Ain Hessainia'),
  ('24', 'Roknia', 'الركنية', 'Hammam Debagh'),
  ('24', 'Sellaoua Announa', 'سلاوة عنونة', 'Ain Hessainia'),
  ('24', 'Tamlouka', 'تاملوكة', 'Ain Makhlouf')
on conflict (wilaya_code, name) do nothing;

-- 25 Constantine
insert into public.communes (wilaya_code, name, name_ar, daira) values
  ('25', 'Ain Abid', 'عين عبيد', 'Ain Abid'),
  ('25', 'Ain Smara', 'عين السمارة', 'El Khroub'),
  ('25', 'Ben Badis', 'أبن باديس الهرية', 'Ain Abid'),
  ('25', 'Beni Hamidane', 'بني حميدان', 'Zighoud Youcef'),
  ('25', 'Constantine', 'قسنطينة', 'Constantine'),
  ('25', 'Didouche Mourad', 'ديدوش مراد', 'Hamma Bouziane'),
  ('25', 'El Khroub', 'الخروب', 'El Khroub'),
  ('25', 'Hamma Bouziane', 'حامة بوزيان', 'Hamma Bouziane'),
  ('25', 'Ibn Ziad', 'ابن زياد', 'Ibn Ziad'),
  ('25', 'Messaoud Boudjeriou', 'بوجريو مسعود', 'Ibn Ziad'),
  ('25', 'Ouled Rahmoun', 'أولاد رحمون', 'El Khroub'),
  ('25', 'Zighoud Youcef', 'زيغود يوسف', 'Zighoud Youcef')
on conflict (wilaya_code, name) do nothing;

-- 26 Médéa
insert into public.communes (wilaya_code, name, name_ar, daira) values
  ('26', 'Ain Boucif', 'عين بوسيف', 'Ain Boucif'),
  ('26', 'Ain Ouksir', 'عين اقصير', 'Chellalat El Adhaoura'),
  ('26', 'Aissaouia', 'العيساوية', 'Tablat'),
  ('26', 'Aziz', 'عزيز', 'Aziz'),
  ('26', 'Baata', 'بعطة', 'El Omaria'),
  ('26', 'Ben Chicao', 'بن شكاو', 'Ouzera'),
  ('26', 'Beni Slimane', 'بني سليمان', 'Beni Slimane'),
  ('26', 'Berrouaghia', 'البرواقية', 'Berrouaghia'),
  ('26', 'Bir Ben Laabed', 'بئر بن عابد', 'Guelb El Kebir'),
  ('26', 'Boghar', 'بوغار', 'Ouled Antar'),
  ('26', 'Bouaiche', 'بوعيش', 'Chahbounia'),
  ('26', 'Bouaichoune', 'بوعيشون', 'Si Mahdjoub'),
  ('26', 'Bouchrahil', 'بوشراحيل', 'Sidi Naamane'),
  ('26', 'Boughzoul', 'بوغزول', 'Chahbounia'),
  ('26', 'Bouskene', 'بوسكن', 'Beni Slimane'),
  ('26', 'Chabounia', 'الشهبونية', 'Chahbounia'),
  ('26', 'Chelalet El Adhaoura', 'شلالة العذاورة', 'Chellalat El Adhaoura'),
  ('26', 'Cheniguel', 'شنيقل', 'Chellalat El Adhaoura'),
  ('26', 'Derrag', 'دراق', 'Aziz'),
  ('26', 'Djouab', 'جواب', 'Souaghi'),
  ('26', 'Draa Esmar', 'ذراع السمار', 'Medea'),
  ('26', 'El Azizia', 'العزيزية', 'El Azizia'),
  ('26', 'El Guelbelkebir', 'القلب الكبير', 'Guelb El Kebir'),
  ('26', 'El Hamdania', 'الحمدانية', 'Ouzera'),
  ('26', 'El Haoudane', 'الحوضان', 'Tablat'),
  ('26', 'El Omaria', 'العمارية', 'El Omaria'),
  ('26', 'El Ouinet', 'العوينات', 'Ain Boucif'),
  ('26', 'Hannacha', 'حناشة', 'Ouamri'),
  ('26', 'Kef Lakhdar', 'الكاف الاخضر', 'Ain Boucif'),
  ('26', 'Khams Djouamaa', 'خمس جوامع', 'Sidi Naamane'),
  ('26', 'Ksar El Boukhari', 'قصر البخاري', 'Ksar El Boukhari'),
  ('26', 'M''fatha', 'مفاتحة', 'Ksar El Boukhari'),
  ('26', 'Maghraoua', 'مغراوة', 'El Azizia'),
  ('26', 'Medea', 'المدية', 'Medea'),
  ('26', 'Medjebar', 'مجبر', 'Seghouane'),
  ('26', 'Mezerana', 'مزغنة', 'Tablat'),
  ('26', 'Mihoub', 'ميهوب', 'El Azizia'),
  ('26', 'Ouamri', 'عوامري', 'Ouamri'),
  ('26', 'Oued Harbil', 'وادي حربيل', 'Ouamri'),
  ('26', 'Ouled Antar', 'أولاد عنتر', 'Ouled Antar'),
  ('26', 'Ouled Bouachra', 'أولاد بوعشرة', 'Si Mahdjoub'),
  ('26', 'Ouled Brahim', 'أولاد إبراهيم', 'El Omaria'),
  ('26', 'Ouled Deid', 'أولاد دايد', 'Berrouaghia'),
  ('26', 'Ouled Emaaraf', 'أولاد امعرف', 'Ain Boucif'),
  ('26', 'Ouled Hellal', 'أولاد هلال', 'Ouled Antar'),
  ('26', 'Oum El Djellil', 'أم الجليل', 'Aziz'),
  ('26', 'Ouzera', 'وزرة', 'Ouzera'),
  ('26', 'Rebaia', 'الربعية', 'Berrouaghia'),
  ('26', 'Saneg', 'السانق', 'Ksar El Boukhari'),
  ('26', 'Sedraya', 'سدراية', 'Guelb El Kebir'),
  ('26', 'Seghouane', 'سغوان', 'Seghouane'),
  ('26', 'Si Mahdjoub', 'سي المحجوب', 'Si Mahdjoub'),
  ('26', 'Sidi Demed', 'سيدي دامد', 'Ain Boucif'),
  ('26', 'Sidi Naamane', 'سيدي نعمان', 'Sidi Naamane'),
  ('26', 'Sidi Rabie', 'سيدي الربيع', 'Beni Slimane'),
  ('26', 'Sidi Zahar', 'سيدي زهار', 'Souaghi'),
  ('26', 'Sidi Ziane', 'سيدي زيان', 'Souaghi'),
  ('26', 'Souagui', 'السواقي', 'Souaghi'),
  ('26', 'Tablat', 'تابلاط', 'Tablat'),
  ('26', 'Tafraout', 'تفراوت', 'Chellalat El Adhaoura'),
  ('26', 'Tamesguida', 'تمسقيدة', 'Medea'),
  ('26', 'Tizi Mahdi', 'تيزي مهدي', 'Ouzera'),
  ('26', 'Tletat Ed Douair', 'ثلاث دوائر', 'Seghouane'),
  ('26', 'Zoubiria', 'الزبيرية', 'Seghouane')
on conflict (wilaya_code, name) do nothing;

-- 27 Mostaganem
insert into public.communes (wilaya_code, name, name_ar, daira) values
  ('27', 'Achaacha', 'عشعاشة', 'Achaacha'),
  ('27', 'Ain-Boudinar', 'عين بودينار', 'Kheir Eddine'),
  ('27', 'Ain-Nouissy', 'عين نويسي', 'Ain Nouicy'),
  ('27', 'Ain-Sidi Cherif', 'عين سيدي الشريف', 'Mesra'),
  ('27', 'Ain-Tedles', 'عين تادلس', 'Ain Tedeles'),
  ('27', 'Benabdelmalek Ramdane', 'بن عبد المالك رمضان', 'Sidi Lakhdar'),
  ('27', 'Bouguirat', 'بوقيراط', 'Bouguirat'),
  ('27', 'Fornaka', 'فرناقة', 'Ain Nouicy'),
  ('27', 'Hadjadj', 'حجاج', 'Sidi Lakhdar'),
  ('27', 'Hassi Mameche', 'حاسي ماماش', 'Hassi Mameche'),
  ('27', 'Hassiane', 'الحسيان (بني ياحي', 'Ain Nouicy'),
  ('27', 'Khadra', 'خضرة', 'Achaacha'),
  ('27', 'Kheir-Eddine', 'خير الدين', 'Kheir Eddine'),
  ('27', 'Mansourah', 'منصورة', 'Mesra'),
  ('27', 'Mazagran', 'مزغران', 'Hassi Mameche'),
  ('27', 'Mesra', 'ماسرة', 'Mesra'),
  ('27', 'Mostaganem', 'مستغانم', 'Mostaganem'),
  ('27', 'Nekmaria', 'نكمارية', 'Achaacha'),
  ('27', 'Oued El Kheir', 'وادي الخير', 'Ain Tedeles'),
  ('27', 'Ouled Boughalem', 'أولاد بوغالم', 'Achaacha'),
  ('27', 'Ouled-Maalah', 'أولاد مع الله', 'Sidi Ali'),
  ('27', 'Safsaf', 'صفصاف', 'Bouguirat'),
  ('27', 'Sayada', 'صيادة', 'Kheir Eddine'),
  ('27', 'Sidi Ali', 'سيدي علي', 'Sidi Ali'),
  ('27', 'Sidi Belaattar', 'سيدي بلعطار', 'Ain Tedeles'),
  ('27', 'Sidi-Lakhdar', 'سيدي لخضر', 'Sidi Lakhdar'),
  ('27', 'Sirat', 'سيرات', 'Bouguirat'),
  ('27', 'Souaflia', 'السوافلية', 'Bouguirat'),
  ('27', 'Sour', 'سور', 'Ain Tedeles'),
  ('27', 'Stidia', 'ستيدية', 'Hassi Mameche'),
  ('27', 'Tazgait', 'تزقايت', 'Sidi Ali'),
  ('27', 'Touahria', 'الطواهرية', 'Mesra')
on conflict (wilaya_code, name) do nothing;

-- 28 M'Sila
insert into public.communes (wilaya_code, name, name_ar, daira) values
  ('28', 'Ain El Hadjel', 'عين الحجل', 'Ain El Hadjel'),
  ('28', 'Ain El Melh', 'عين الملح', 'Ain El Melh'),
  ('28', 'Ain Fares', 'عين فارس', 'Ain El Melh'),
  ('28', 'Ain Khadra', 'عين الخضراء', 'Magra'),
  ('28', 'Ain Rich', 'عين الريش', 'Ain El Melh'),
  ('28', 'Belaiba', 'بلعايبة', 'Magra'),
  ('28', 'Ben Srour', 'بن سرور', 'Ben Srour'),
  ('28', 'Beni Ilmane', 'بني يلمان', 'Sidi Aissa'),
  ('28', 'Benzouh', 'بن زوه', 'Ouled Sidi Brahim'),
  ('28', 'Berhoum', 'برهوم', 'Magra'),
  ('28', 'Bir Foda', 'بئر فضة', 'Ain El Melh'),
  ('28', 'Bou Saada', 'بوسعادة', 'Bousaada'),
  ('28', 'Bouti Sayeh', 'بوطي السايح', 'Sidi Aissa'),
  ('28', 'Chellal', 'شلال', 'Chellal'),
  ('28', 'Dehahna', 'دهاهنة', 'Magra'),
  ('28', 'Djebel Messaad', 'جبل مساعد', 'Djebel Messaad'),
  ('28', 'El Hamel', 'الهامل', 'Bousaada'),
  ('28', 'El Houamed', 'الحوامد', 'Khoubana'),
  ('28', 'Hammam Dalaa', 'حمام الضلعة', 'Hammam Dalaa'),
  ('28', 'Khettouti Sed-El-Jir', 'خطوطي سد الجير', 'Chellal'),
  ('28', 'Khoubana', 'خبانة', 'Khoubana'),
  ('28', 'M''cif', 'مسيف', 'Khoubana'),
  ('28', 'M''sila', 'المسيلة', 'M''sila'),
  ('28', 'M''tarfa', 'المطارفة', 'Ouled Derradj'),
  ('28', 'Maadid', 'المعاضيد', 'Ouled Derradj'),
  ('28', 'Maarif', 'معاريف', 'Chellal'),
  ('28', 'Magra', 'مقرة', 'Magra'),
  ('28', 'Medjedel', 'امجدل', 'Medjedel'),
  ('28', 'Menaa', 'مناعة', 'Medjedel'),
  ('28', 'Mohamed Boudiaf', 'محمد بوضياف', 'Ben Srour'),
  ('28', 'Ouanougha', 'ونوغة', 'Hammam Dalaa'),
  ('28', 'Ouled Addi Guebala', 'أولاد عدي لقبالة', 'Ouled Derradj'),
  ('28', 'Ouled Derradj', 'أولاد دراج', 'Ouled Derradj'),
  ('28', 'Ouled Madhi', 'أولاد ماضي', 'Chellal'),
  ('28', 'Ouled Mansour', 'أولاد منصور', 'Hammam Dalaa'),
  ('28', 'Ouled Sidi Brahim', 'أولاد سيدي ابراهيم', 'Ouled Sidi Brahim'),
  ('28', 'Ouled Slimane', 'أولاد سليمان', 'Ben Srour'),
  ('28', 'Oulteme', 'ولتام', 'Bousaada'),
  ('28', 'Sidi Aissa', 'سيدي عيسى', 'Sidi Aissa'),
  ('28', 'Sidi Ameur', 'سيدي عامر', 'Sidi Ameur'),
  ('28', 'Sidi Hadjeres', 'سيدي هجرس', 'Ain El Hadjel'),
  ('28', 'Sidi M''hamed', 'سيدي امحمد', 'Ain El Melh'),
  ('28', 'Slim', 'سليم', 'Djebel Messaad'),
  ('28', 'Souamaa', 'السوامع', 'Ouled Derradj'),
  ('28', 'Tamsa', 'تامسة', 'Sidi Ameur'),
  ('28', 'Tarmount', 'تارمونت', 'Hammam Dalaa'),
  ('28', 'Zarzour', 'زرزور', 'Ben Srour')
on conflict (wilaya_code, name) do nothing;

-- 29 Mascara
insert into public.communes (wilaya_code, name, name_ar, daira) values
  ('29', 'Ain Fares', 'عين فارس', 'Ain Fares'),
  ('29', 'Ain Fekan', 'عين فكان', 'Ain Fekan'),
  ('29', 'Ain Ferah', 'عين فراح', 'Oued El Abtal'),
  ('29', 'Ain Frass', 'عين أفرص', 'Ain Fekan'),
  ('29', 'Alaimia', 'العلايمية', 'Oggaz'),
  ('29', 'Aouf', 'عوف', 'Aouf'),
  ('29', 'Benian', 'بنيان', 'Aouf'),
  ('29', 'Bou Henni', 'بوهني', 'Sig'),
  ('29', 'Bouhanifia', 'بوحنيفية', 'Bouhanifia'),
  ('29', 'Chorfa', 'الشرفاء', 'Sig'),
  ('29', 'El Bordj', 'البرج', 'El Bordj'),
  ('29', 'El Gaada', 'القعدة', 'Zahana'),
  ('29', 'El Ghomri', 'الغمري', 'Mohammadia'),
  ('29', 'El Gueitena', 'القطنة', 'Bouhanifia'),
  ('29', 'El Hachem', 'الحشم', 'Hachem'),
  ('29', 'El Keurt', 'القرط', 'Tizi'),
  ('29', 'El Mamounia', 'المأمونية', 'Ain Fares'),
  ('29', 'El Menaouer', 'المنور', 'El Bordj'),
  ('29', 'Ferraguig', 'فراقيق', 'Mohammadia'),
  ('29', 'Froha', 'فروحة', 'Tizi'),
  ('29', 'Gharrous', 'غروس', 'Aouf'),
  ('29', 'Ghriss', 'غريس', 'Ghriss'),
  ('29', 'Guerdjoum', 'قرجوم', 'Oued Taria'),
  ('29', 'Hacine', 'حسين', 'Bouhanifia'),
  ('29', 'Khalouia', 'خلوية', 'El Bordj'),
  ('29', 'Makhda', 'ماقضة', 'Ghriss'),
  ('29', 'Maoussa', 'ماوسة', 'Ghriss'),
  ('29', 'Mascara', 'معسكر', 'Mascara'),
  ('29', 'Matemore', 'المطمور', 'Ghriss'),
  ('29', 'Mocta-Douz', 'مقطع الدوز', 'Mohammadia'),
  ('29', 'Mohammadia', 'المحمدية', 'Mohammadia'),
  ('29', 'Nesmot', 'نسمط', 'Hachem'),
  ('29', 'Oggaz', 'عقاز', 'Oggaz'),
  ('29', 'Oued El Abtal', 'وادي الأبطال', 'Oued El Abtal'),
  ('29', 'Oued Taria', 'وادي التاغية', 'Oued Taria'),
  ('29', 'Ras El Ain Amirouche', 'رأس عين عميروش', 'Oggaz'),
  ('29', 'Sedjerara', 'سجرارة', 'Mohammadia'),
  ('29', 'Sehailia', 'السهايلية', 'Tighennif'),
  ('29', 'Sidi Abdeldjebar', 'سيدي عبد الجبار', 'Oued El Abtal'),
  ('29', 'Sidi Abdelmoumene', 'سيدي عبد المومن', 'Mohammadia'),
  ('29', 'Sidi Boussaid', 'سيدي بوسعيد', 'Ghriss'),
  ('29', 'Sidi Kada', 'سيدي قادة', 'Tighennif'),
  ('29', 'Sig', 'سيق', 'Sig'),
  ('29', 'Tighennif', 'تيغنيف', 'Tighennif'),
  ('29', 'Tizi', 'تيزي', 'Tizi'),
  ('29', 'Zahana', 'زهانة', 'Zahana'),
  ('29', 'Zelamta', 'زلامطة', 'Hachem')
on conflict (wilaya_code, name) do nothing;

-- 30 Ouargla
insert into public.communes (wilaya_code, name, name_ar, daira) values
  ('30', 'Ain Beida', 'عين البيضاء', 'Sidi Khouiled'),
  ('30', 'El Borma', 'البرمة', 'El Borma'),
  ('30', 'Hassi Ben Abdellah', 'حاسي بن عبد الله', 'Sidi Khouiled'),
  ('30', 'Hassi Messaoud', 'حاسي مسعود', 'Hassi Messaoud'),
  ('30', 'N''goussa', 'انقوسة', 'N''goussa'),
  ('30', 'Ouargla', 'ورقلة', 'Ouargla'),
  ('30', 'Rouissat', 'الرويسات', 'Ouargla'),
  ('30', 'Sidi Khouiled', 'سيدي خويلد', 'Sidi Khouiled')
on conflict (wilaya_code, name) do nothing;

-- 31 Oran
insert into public.communes (wilaya_code, name, name_ar, daira) values
  ('31', 'Ain Biya', 'عين البية', 'Bethioua'),
  ('31', 'Ain Kerma', 'عين الكرمة', 'Boutlelis'),
  ('31', 'Ain Turk', 'عين الترك', 'Ain Turk'),
  ('31', 'Arzew', 'أرزيو', 'Arzew'),
  ('31', 'Ben Freha', 'بن فريحة', 'Gdyel'),
  ('31', 'Bethioua', 'بطيوة', 'Bethioua'),
  ('31', 'Bir El Djir', 'بئر الجير', 'Bir El Djir'),
  ('31', 'Boufatis', 'بوفاتيس', 'Oued Tlelat'),
  ('31', 'Bousfer', 'بوسفر', 'Ain Turk'),
  ('31', 'Boutlelis', 'بوتليليس', 'Boutlelis'),
  ('31', 'El Ancor', 'العنصر', 'Ain Turk'),
  ('31', 'El Braya', 'البراية', 'Oued Tlelat'),
  ('31', 'El Kerma', 'الكرمة', 'Es Senia'),
  ('31', 'Es Senia', 'السانية', 'Es Senia'),
  ('31', 'Gdyel', 'قديل', 'Gdyel'),
  ('31', 'Hassi Ben Okba', 'حاسي بن عقبة', 'Bir El Djir'),
  ('31', 'Hassi Bounif', 'حاسي بونيف', 'Bir El Djir'),
  ('31', 'Hassi Mefsoukh', 'حاسي مفسوخ', 'Gdyel'),
  ('31', 'Marsat El Hadjadj', 'مرسى الحجاج', 'Bethioua'),
  ('31', 'Mers El Kebir', 'المرسى الكبير', 'Ain Turk'),
  ('31', 'Messerghin', 'مسرغين', 'Boutlelis'),
  ('31', 'Oran', 'وهران', 'Oran'),
  ('31', 'Oued Tlelat', 'وادي تليلات', 'Oued Tlelat'),
  ('31', 'Sidi Ben Yebka', 'سيدي بن يبقى', 'Arzew'),
  ('31', 'Sidi Chami', 'سيدي الشحمي', 'Es Senia'),
  ('31', 'Tafraoui', 'طفراوي', 'Oued Tlelat')
on conflict (wilaya_code, name) do nothing;

-- 32 El Bayadh
insert into public.communes (wilaya_code, name, name_ar, daira) values
  ('32', 'Ain El Orak', 'عين العراك', 'Labiodh Sidi Cheikh'),
  ('32', 'Arbaouat', 'اربوات', 'Labiodh Sidi Cheikh'),
  ('32', 'Boualem', 'بوعلام', 'Boualem'),
  ('32', 'Bougtoub', 'بوقطب', 'Bougtoub'),
  ('32', 'Boussemghoun', 'بوسمغون', 'Boussemghoun'),
  ('32', 'Brezina', 'بريزينة', 'Brezina'),
  ('32', 'Cheguig', 'الشقيق', 'Rogassa'),
  ('32', 'Chellala', 'شلالة', 'Chellala'),
  ('32', 'El Bayadh', 'البيض', 'El Bayadh'),
  ('32', 'El Bnoud', 'البنود', 'Labiodh Sidi Cheikh'),
  ('32', 'El Kheiter', 'الخيثر', 'Bougtoub'),
  ('32', 'El Mehara', 'المحرة', 'Chellala'),
  ('32', 'Ghassoul', 'الغاسول', 'Brezina'),
  ('32', 'Kef El Ahmar', 'الكاف الأحمر', 'Rogassa'),
  ('32', 'Krakda', 'كراكدة', 'Brezina'),
  ('32', 'Labiodh Sidi Cheikh', 'الأبيض سيدي الشيخ', 'Labiodh Sidi Cheikh'),
  ('32', 'Rogassa', 'رقاصة', 'Rogassa'),
  ('32', 'Sidi Ameur', 'سيدي عامر', 'Boualem'),
  ('32', 'Sidi Slimane', 'سيدي سليمان', 'Boualem'),
  ('32', 'Sidi Tiffour', 'سيدي طيفور', 'Boualem'),
  ('32', 'Stitten', 'ستيتن', 'Boualem'),
  ('32', 'Tousmouline', 'توسمولين', 'Bougtoub')
on conflict (wilaya_code, name) do nothing;

-- 33 Illizi
insert into public.communes (wilaya_code, name, name_ar, daira) values
  ('33', 'Bordj Omar Driss', 'برج عمر إدريس', 'In Amenas'),
  ('33', 'Debdeb', 'دبداب', 'In Amenas'),
  ('33', 'Illizi', 'إيليزي', 'Illizi'),
  ('33', 'In Amenas', 'إن أمناس', 'In Amenas')
on conflict (wilaya_code, name) do nothing;

-- 34 Bordj Bou Arreridj
insert into public.communes (wilaya_code, name, name_ar, daira) values
  ('34', 'Ain Taghrout', 'عين تاغروت', 'Ain Taghrout'),
  ('34', 'Ain Tesra', 'عين تسرة', 'Ras El Oued'),
  ('34', 'B. B. Arreridj', 'برج بوعريرج', 'Bordj Bou Arreridj'),
  ('34', 'Belimour', 'بليمور', 'Bordj Ghedir'),
  ('34', 'Ben Daoud', 'بن داود', 'Mansourah'),
  ('34', 'Bir Kasdali', 'بئر قاصد علي', 'Bir Kasdali'),
  ('34', 'Bordj Ghedir', 'برج الغدير', 'Bordj Ghedir'),
  ('34', 'Bordj Zemmoura', 'برج زمورة', 'Bordj Zemmoura'),
  ('34', 'Colla', 'القلة', 'Djaafra'),
  ('34', 'Djaafra', 'جعافرة', 'Djaafra'),
  ('34', 'El Achir', 'الياشير', 'Medjana'),
  ('34', 'El Annasseur', 'العناصر', 'Bordj Ghedir'),
  ('34', 'El Euch', 'العش', 'El Hamadia'),
  ('34', 'El M''hir', 'المهير', 'Mansourah'),
  ('34', 'El Main', 'الماين', 'Djaafra'),
  ('34', 'Elhammadia', 'الحمادية', 'El Hamadia'),
  ('34', 'Ghailasa', 'غيلاسة', 'Bordj Ghedir'),
  ('34', 'Haraza', 'حرازة', 'Mansourah'),
  ('34', 'Hasnaoua', 'حسناوة', 'Medjana'),
  ('34', 'Khelil', 'خليل', 'Bir Kasdali'),
  ('34', 'Ksour', 'القصور', 'El Hamadia'),
  ('34', 'Mansoura', 'المنصورة', 'Mansourah'),
  ('34', 'Medjana', 'مجانة', 'Medjana'),
  ('34', 'Ouled Brahem', 'أولاد أبراهم', 'Ras El Oued'),
  ('34', 'Ouled Dahmane', 'أولاد دحمان', 'Bordj Zemmoura'),
  ('34', 'Ouled Sidi-Brahim', 'أولاد سيدي ابراهيم', 'Mansourah'),
  ('34', 'Rabta', 'الرابطة', 'El Hamadia'),
  ('34', 'Ras El Oued', 'رأس الوادي', 'Ras El Oued'),
  ('34', 'Sidi-Embarek', 'سيدي أمبارك', 'Bir Kasdali'),
  ('34', 'Taglait', 'تقلعيت', 'Bordj Ghedir'),
  ('34', 'Tassamert', 'تسامرت', 'Bordj Zemmoura'),
  ('34', 'Tefreg', 'تفرق', 'Djaafra'),
  ('34', 'Teniet En Nasr', 'ثنية النصر', 'Medjana'),
  ('34', 'Tixter', 'تيكستار', 'Ain Taghrout')
on conflict (wilaya_code, name) do nothing;

-- 35 Boumerdès
insert into public.communes (wilaya_code, name, name_ar, daira) values
  ('35', 'Afir', 'أعفير', 'Dellys'),
  ('35', 'Ammal', 'عمال', 'Thenia'),
  ('35', 'Baghlia', 'بغلية', 'Baghlia'),
  ('35', 'Ben Choud', 'بن شود', 'Dellys'),
  ('35', 'Beni Amrane', 'بني عمران', 'Thenia'),
  ('35', 'Bordj Menaiel', 'برج منايل', 'Bordj Menaiel'),
  ('35', 'Boudouaou', 'بودواو', 'Boudouaou'),
  ('35', 'Boudouaou El Bahri', 'بودواو البحري', 'Boudouaou'),
  ('35', 'Boumerdes', 'بومرداس', 'Boumerdes'),
  ('35', 'Bouzegza Keddara', 'بوزقزة قدارة', 'Boudouaou'),
  ('35', 'Chabet El Ameur', 'شعبة العامر', 'Isser'),
  ('35', 'Corso', 'قورصو', 'Boumerdes'),
  ('35', 'Dellys', 'دلس', 'Dellys'),
  ('35', 'Djinet', 'جنات', 'Bordj Menaiel'),
  ('35', 'El Kharrouba', 'الخروبة', 'Boudouaou'),
  ('35', 'Hammedi', 'حمادي', 'Khemis El Khechna'),
  ('35', 'Isser', 'يسر', 'Isser'),
  ('35', 'Khemis El Khechna', 'خميس الخشنة', 'Khemis El Khechna'),
  ('35', 'Larbatache', 'الاربعطاش', 'Khemis El Khechna'),
  ('35', 'Leghata', 'لقاطة', 'Bordj Menaiel'),
  ('35', 'Naciria', 'الناصرية', 'Naciria'),
  ('35', 'Ouled Aissa', 'أولاد عيسى', 'Naciria'),
  ('35', 'Ouled Hedadj', 'أولاد هداج', 'Boudouaou'),
  ('35', 'Ouled Moussa', 'أولاد موسى', 'Khemis El Khechna'),
  ('35', 'Si Mustapha', 'سي مصطفى', 'Isser'),
  ('35', 'Sidi Daoud', 'سيدي داود', 'Baghlia'),
  ('35', 'Souk El Had', 'سوق الحد', 'Thenia'),
  ('35', 'Taourga', 'تاورقة', 'Baghlia'),
  ('35', 'Thenia', 'الثنية', 'Thenia'),
  ('35', 'Tidjelabine', 'تيجلابين', 'Boumerdes'),
  ('35', 'Timezrit', 'تيمزريت', 'Isser'),
  ('35', 'Zemmouri', 'زموري', 'Bordj Menaiel')
on conflict (wilaya_code, name) do nothing;

-- 36 El Tarf
insert into public.communes (wilaya_code, name, name_ar, daira) values
  ('36', 'Ain El Assel', 'عين العسل', 'El Tarf'),
  ('36', 'Ain Kerma', 'عين الكرمة', 'Bouhadjar'),
  ('36', 'Asfour', 'عصفور', 'Besbes'),
  ('36', 'Ben M Hidi', 'بن مهيدي', 'Ben M''hidi'),
  ('36', 'Berrihane', 'بريحان', 'Ben M''hidi'),
  ('36', 'Besbes', 'البسباس', 'Besbes'),
  ('36', 'Bougous', 'بوقوس', 'El Tarf'),
  ('36', 'Bouhadjar', 'بوحجار', 'Bouhadjar'),
  ('36', 'Bouteldja', 'بوثلجة', 'Bouteldja'),
  ('36', 'Chebaita Mokhtar', 'شبيطة مختار', 'Drean'),
  ('36', 'Chefia', 'الشافية', 'Bouteldja'),
  ('36', 'Chihani', 'شحاني', 'Drean'),
  ('36', 'Drean', 'الذرعـان', 'Drean'),
  ('36', 'Echatt', 'الشط', 'Ben M''hidi'),
  ('36', 'El Aioun', 'العيون', 'El Kala'),
  ('36', 'El Kala', 'القالة', 'El Kala'),
  ('36', 'El Tarf', 'الطارف', 'El Tarf'),
  ('36', 'Hammam Beni Salah', 'حمام بني صالح', 'Bouhadjar'),
  ('36', 'Lac Des Oiseaux', 'بحيرة الطيور', 'Bouteldja'),
  ('36', 'Oued Zitoun', 'وادي الزيتون', 'Bouhadjar'),
  ('36', 'Raml Souk', 'رمل السوق', 'El Kala'),
  ('36', 'Souarekh', 'السوارخ', 'El Kala'),
  ('36', 'Zerizer', 'زريزر', 'Besbes'),
  ('36', 'Zitouna', 'الزيتونة', 'El Tarf')
on conflict (wilaya_code, name) do nothing;

-- 37 Tindouf
insert into public.communes (wilaya_code, name, name_ar, daira) values
  ('37', 'Oum El Assel', 'أم العسل', 'Tindouf'),
  ('37', 'Tindouf', 'تندوف', 'Tindouf')
on conflict (wilaya_code, name) do nothing;

-- 38 Tissemsilt
insert into public.communes (wilaya_code, name, name_ar, daira) values
  ('38', 'Ammari', 'عماري', 'Ammari'),
  ('38', 'Beni Chaib', 'بني شعيب', 'Bordj Bounaama'),
  ('38', 'Beni Lahcene', 'بني لحسن', 'Bordj Bounaama'),
  ('38', 'Bordj Bounaama', 'برج بونعامة', 'Bordj Bounaama'),
  ('38', 'Bordj El Emir Abdelkader', 'برج الأمير عبد القادر', 'Bordj Emir Abdelkader'),
  ('38', 'Boucaid', 'بوقائد', 'Lazharia'),
  ('38', 'Khemisti', 'خميستي', 'Khemisti'),
  ('38', 'Larbaa', 'الأربعاء', 'Lazharia'),
  ('38', 'Lardjem', 'لرجام', 'Lardjem'),
  ('38', 'Layoune', 'العيون', 'Khemisti'),
  ('38', 'Lazharia', 'الأزهرية', 'Lazharia'),
  ('38', 'Maacem', 'المعاصم', 'Ammari'),
  ('38', 'Melaab', 'الملعب', 'Lardjem'),
  ('38', 'Ouled Bessam', 'أولاد بسام', 'Tissemsilt'),
  ('38', 'Sidi Abed', 'سيدي عابد', 'Ammari'),
  ('38', 'Sidi Boutouchent', 'سيدي بوتوشنت', 'Theniet El Had'),
  ('38', 'Sidi Lantri', 'سيدي العنتري', 'Lardjem'),
  ('38', 'Sidi Slimane', 'سيدي سليمان', 'Bordj Bounaama'),
  ('38', 'Tamellahet', 'تملاحت', 'Lardjem'),
  ('38', 'Theniet El Had', 'ثنية الاحد', 'Theniet El Had'),
  ('38', 'Tissemsilt', 'تيسمسيلت', 'Tissemsilt'),
  ('38', 'Youssoufia', 'اليوسفية', 'Bordj Emir Abdelkader')
on conflict (wilaya_code, name) do nothing;

-- 39 El Oued
insert into public.communes (wilaya_code, name, name_ar, daira) values
  ('39', 'Bayadha', 'البياضة', 'Bayadha'),
  ('39', 'Ben Guecha', 'بن  قشة', 'Taleb Larbi'),
  ('39', 'Debila', 'الدبيلة', 'Debila'),
  ('39', 'Douar El Maa', 'دوار الماء', 'Taleb Larbi'),
  ('39', 'El Ogla', 'العقلة', 'Robbah'),
  ('39', 'El-Oued', 'الوادي', 'El Oued'),
  ('39', 'Guemar', 'قمار', 'Guemar'),
  ('39', 'Hamraia', 'الحمراية', 'Reguiba'),
  ('39', 'Hassani Abdelkrim', 'حساني عبد الكريم', 'Debila'),
  ('39', 'Hassi Khalifa', 'حاسي خليفة', 'Hassi Khalifa'),
  ('39', 'Kouinine', 'كوينين', 'El Oued'),
  ('39', 'Magrane', 'المقرن', 'Magrane'),
  ('39', 'Mih Ouansa', 'اميه وانسة', 'Mih Ouensa'),
  ('39', 'Nakhla', 'النخلة', 'Robbah'),
  ('39', 'Oued El Alenda', 'وادي العلندة', 'Mih Ouensa'),
  ('39', 'Ourmes', 'ورماس', 'Guemar'),
  ('39', 'Reguiba', 'الرقيبة', 'Reguiba'),
  ('39', 'Robbah', 'الرباح', 'Robbah'),
  ('39', 'Sidi Aoun', 'سيدي عون', 'Magrane'),
  ('39', 'Taghzout', 'تغزوت', 'Guemar'),
  ('39', 'Taleb Larbi', 'الطالب العربي', 'Taleb Larbi'),
  ('39', 'Trifaoui', 'الطريفاوي', 'Hassi Khalifa')
on conflict (wilaya_code, name) do nothing;

-- 40 Khenchela
insert into public.communes (wilaya_code, name, name_ar, daira) values
  ('40', 'Ain Touila', 'عين الطويلة', 'Ain Touila'),
  ('40', 'Babar', 'بابار', 'Babar'),
  ('40', 'Baghai', 'بغاي', 'El Hamma'),
  ('40', 'Bouhmama', 'بوحمامة', 'Bouhmama'),
  ('40', 'Chechar', 'ششار', 'Chechar'),
  ('40', 'Chelia', 'شلية', 'Bouhmama'),
  ('40', 'Djellal', 'جلال', 'Chechar'),
  ('40', 'El Hamma', 'الحامة', 'El Hamma'),
  ('40', 'El Mahmal', 'المحمل', 'Ouled Rechache'),
  ('40', 'El Oueldja', 'الولجة', 'Chechar'),
  ('40', 'Ensigha', 'انسيغة', 'El Hamma'),
  ('40', 'Kais', 'قايس', 'Kais'),
  ('40', 'Khenchela', 'خنشلة', 'Khenchela'),
  ('40', 'Khirane', 'خيران', 'Chechar'),
  ('40', 'M''sara', 'مصارة', 'Bouhmama'),
  ('40', 'M''toussa', 'متوسة', 'Ain Touila'),
  ('40', 'Ouled Rechache', 'أولاد رشاش', 'Ouled Rechache'),
  ('40', 'Remila', 'الرميلة', 'Kais'),
  ('40', 'Tamza', 'طامزة', 'El Hamma'),
  ('40', 'Taouzianat', 'تاوزيانت', 'Kais'),
  ('40', 'Yabous', 'يابوس', 'Bouhmama')
on conflict (wilaya_code, name) do nothing;

-- 41 Souk Ahras
insert into public.communes (wilaya_code, name, name_ar, daira) values
  ('41', 'Ain Soltane', 'عين سلطان', 'Sedrata'),
  ('41', 'Ain Zana', 'عين الزانة', 'Ouled Driss'),
  ('41', 'Bir Bouhouche', 'بئر بوحوش', 'Bir Bouhouche'),
  ('41', 'Drea', 'الدريعة', 'Taoura'),
  ('41', 'Haddada', 'الحدادة', 'Haddada'),
  ('41', 'Hanencha', 'الحنانشة', 'Mechroha'),
  ('41', 'Khedara', 'الخضارة', 'Haddada'),
  ('41', 'Khemissa', 'خميسة', 'Sedrata'),
  ('41', 'M''daourouche', 'مداوروش', 'M''daourouche'),
  ('41', 'Machroha', 'المشروحة', 'Mechroha'),
  ('41', 'Merahna', 'المراهنة', 'Merahna'),
  ('41', 'Oued Kebrit', 'وادي الكبريت', 'Oum El Adhaim'),
  ('41', 'Ouillen', 'ويلان', 'Merahna'),
  ('41', 'Ouled Driss', 'أولاد إدريس', 'Ouled Driss'),
  ('41', 'Ouled Moumen', 'أولاد مومن', 'Haddada'),
  ('41', 'Oum El Adhaim', 'أم العظايم', 'Oum El Adhaim'),
  ('41', 'Ragouba', 'الراقوبة', 'M''daourouche'),
  ('41', 'Safel El Ouiden', 'سافل الويدان', 'Bir Bouhouche'),
  ('41', 'Sedrata', 'سدراتة', 'Sedrata'),
  ('41', 'Sidi Fredj', 'سيدي فرج', 'Merahna'),
  ('41', 'Souk Ahras', 'سوق أهراس', 'Souk Ahras'),
  ('41', 'Taoura', 'تاورة', 'Taoura'),
  ('41', 'Terraguelt', 'ترقالت', 'Oum El Adhaim'),
  ('41', 'Tiffech', 'تيفاش', 'M''daourouche'),
  ('41', 'Zaarouria', 'الزعرورية', 'Taoura'),
  ('41', 'Zouabi', 'الزوابي', 'Bir Bouhouche')
on conflict (wilaya_code, name) do nothing;

-- 42 Tipaza
insert into public.communes (wilaya_code, name, name_ar, daira) values
  ('42', 'Aghbal', 'أغبال', 'Gouraya'),
  ('42', 'Ahmer El Ain', 'أحمر العين', 'Ahmar El Ain'),
  ('42', 'Ain Tagourait', 'عين تاقورايت', 'Bou Ismail'),
  ('42', 'Attatba', 'الحطاطبة', 'Kolea'),
  ('42', 'Beni Mileuk', 'بني ميلك', 'Damous'),
  ('42', 'Bou Haroun', 'بوهارون', 'Bou Ismail'),
  ('42', 'Bou Ismail', 'بواسماعيل', 'Bou Ismail'),
  ('42', 'Bourkika', 'بورقيقة', 'Ahmar El Ain'),
  ('42', 'Chaiba', 'الشعيبة', 'Kolea'),
  ('42', 'Cherchell', 'شرشال', 'Cherchell'),
  ('42', 'Damous', 'الداموس', 'Damous'),
  ('42', 'Douaouda', 'دواودة', 'Fouka'),
  ('42', 'Fouka', 'فوكة', 'Fouka'),
  ('42', 'Gouraya', 'قوراية', 'Gouraya'),
  ('42', 'Hadjout', 'حجوط', 'Hadjout'),
  ('42', 'Hadjret Ennous', 'حجرة النص', 'Cherchell'),
  ('42', 'Khemisti', 'خميستي', 'Bou Ismail'),
  ('42', 'Kolea', 'القليعة', 'Kolea'),
  ('42', 'Larhat', 'الأرهاط', 'Damous'),
  ('42', 'Menaceur', 'مناصر', 'Sidi Amar'),
  ('42', 'Merad', 'مراد', 'Hadjout'),
  ('42', 'Messelmoun', 'مسلمون', 'Gouraya'),
  ('42', 'Nador', 'الناظور', 'Sidi Amar'),
  ('42', 'Sidi Ghiles', 'سيدي غيلاس', 'Cherchell'),
  ('42', 'Sidi Rached', 'سيدي راشد', 'Ahmar El Ain'),
  ('42', 'Sidi Semiane', 'سيدي سميان', 'Cherchell'),
  ('42', 'Sidi-Amar', 'سيدي عامر', 'Sidi Amar'),
  ('42', 'Tipaza', 'تيبازة', 'Tipaza')
on conflict (wilaya_code, name) do nothing;

-- 43 Mila
insert into public.communes (wilaya_code, name, name_ar, daira) values
  ('43', 'Ahmed Rachedi', 'أحمد راشدي', 'Oued Endja'),
  ('43', 'Ain Beida Harriche', ' عين البيضاء أحريش', 'Ain Beida Harriche'),
  ('43', 'Ain Mellouk', 'عين الملوك', 'Chelghoum Laid'),
  ('43', 'Ain Tine', 'عين التين', 'Mila'),
  ('43', 'Amira Arres', 'اعميرة اراس', 'Terrai Bainen'),
  ('43', 'Benyahia Abderrahmane', 'بن يحي عبد الرحمن', 'Tadjenanet'),
  ('43', 'Bouhatem', 'بوحاتم', 'Bouhatem'),
  ('43', 'Chelghoum Laid', 'شلغوم العيد', 'Chelghoum Laid'),
  ('43', 'Chigara', 'الشيقارة', 'Sidi Merouane'),
  ('43', 'Derrahi Bousselah', 'دراحي بوصلاح', 'Bouhatem'),
  ('43', 'El Ayadi Barbes', 'العياضي برباس', 'Ain Beida Harriche'),
  ('43', 'El Mechira', 'مشيرة', 'Teleghma'),
  ('43', 'Ferdjioua', 'فرجيوة', 'Ferdjioua'),
  ('43', 'Grarem Gouga', 'القرارم قوقة', 'Grarem Gouga'),
  ('43', 'Hamala', 'حمالة', 'Grarem Gouga'),
  ('43', 'Mila', 'ميلة', 'Mila'),
  ('43', 'Minar Zarza', 'مينار زارزة', 'Tassadane Haddada'),
  ('43', 'Oued Athmenia', 'وادي العثمانية', 'Chelghoum Laid'),
  ('43', 'Oued Endja', 'وادي النجاء', 'Oued Endja'),
  ('43', 'Oued Seguen', 'وادي سقان', 'Teleghma'),
  ('43', 'Ouled Khalouf', 'أولاد اخلوف', 'Tadjenanet'),
  ('43', 'Rouached', 'الرواشد', 'Rouached'),
  ('43', 'Sidi Khelifa', 'سيدي خليفة', 'Mila'),
  ('43', 'Sidi Merouane', 'سيدي مروان', 'Sidi Merouane'),
  ('43', 'Tadjenanet', 'تاجنانت', 'Tadjenanet'),
  ('43', 'Tassadane Haddada', 'تسدان حدادة', 'Tassadane Haddada'),
  ('43', 'Tassala Lematai', 'تسالة لمطاعي', 'Terrai Bainen'),
  ('43', 'Teleghma', 'التلاغمة', 'Teleghma'),
  ('43', 'Terrai Bainen', 'ترعي باينان', 'Terrai Bainen'),
  ('43', 'Tiberguent', 'تيبرقنت', 'Rouached'),
  ('43', 'Yahia Beniguecha', 'يحي بني قشة', 'Ferdjioua'),
  ('43', 'Zeghaia', 'زغاية', 'Oued Endja')
on conflict (wilaya_code, name) do nothing;

-- 44 Aïn Defla
insert into public.communes (wilaya_code, name, name_ar, daira) values
  ('44', 'Ain-Benian', 'عين البنيان', 'Hammam Righa'),
  ('44', 'Ain-Bouyahia', 'عين بويحيى', 'El Abadia'),
  ('44', 'Ain-Defla', 'عين الدفلى', 'Ain Defla'),
  ('44', 'Ain-Lechiakh', 'عين الاشياخ', 'Ain Lechiakh'),
  ('44', 'Ain-Soltane', 'عين السلطان', 'Ain Lechiakh'),
  ('44', 'Ain-Torki', 'عين التركي', 'Hammam Righa'),
  ('44', 'Arib', 'عريب', 'El Amra'),
  ('44', 'Bathia', 'بطحية', 'Bathia'),
  ('44', 'Belaas', 'بلعاص', 'Bathia'),
  ('44', 'Ben Allal', 'بن علال', 'Miliana'),
  ('44', 'Bir-Ould-Khelifa', 'بئر ولد خليفة', 'Bordj El Emir Khaled'),
  ('44', 'Birbouche', 'بربوش', 'Djendel'),
  ('44', 'Bordj-Emir-Khaled', 'برج الأمير خالد', 'Bordj El Emir Khaled'),
  ('44', 'Boumedfaa', 'بومدفع', 'Boumedfaa'),
  ('44', 'Bourached', 'بوراشد', 'Djelida'),
  ('44', 'Djelida', 'جليدة', 'Djelida'),
  ('44', 'Djemaa Ouled Cheikh', 'جمعة أولاد الشيخ', 'Djelida'),
  ('44', 'Djendel', 'جندل', 'Djendel'),
  ('44', 'El-Abadia', 'العبادية', 'El Abadia'),
  ('44', 'El-Amra', 'العامرة', 'El Amra'),
  ('44', 'El-Attaf', 'العطاف', 'El Attaf'),
  ('44', 'El-Maine', 'الماين', 'Rouina'),
  ('44', 'Hammam-Righa', 'حمام ريغة', 'Hammam Righa'),
  ('44', 'Hassania', 'الحسانية', 'Bathia'),
  ('44', 'Hoceinia', 'الحسينية', 'Boumedfaa'),
  ('44', 'Khemis-Miliana', 'خميس مليانة', 'Khemis'),
  ('44', 'Mekhatria', 'المخاطرية', 'El Amra'),
  ('44', 'Miliana', 'مليانة', 'Miliana'),
  ('44', 'Oued Chorfa', 'وادي الشرفاء', 'Djendel'),
  ('44', 'Oued Djemaa', 'واد الجمعة', 'Ain Lechiakh'),
  ('44', 'Rouina', 'الروينة', 'Rouina'),
  ('44', 'Sidi-Lakhdar', 'سيدي الأخضر', 'Khemis'),
  ('44', 'Tacheta Zegagha', 'تاشتة زقاغة', 'El Abadia'),
  ('44', 'Tarik-Ibn-Ziad', 'طارق بن زياد', 'Bordj El Emir Khaled'),
  ('44', 'Tiberkanine', 'تبركانين', 'El Attaf'),
  ('44', 'Zeddine', 'زدين', 'Rouina')
on conflict (wilaya_code, name) do nothing;

-- 45 Naâma
insert into public.communes (wilaya_code, name, name_ar, daira) values
  ('45', 'Ain Ben Khelil', 'عين بن خليل', 'Mecheria'),
  ('45', 'Ain Sefra', 'عين الصفراء', 'Ain Sefra'),
  ('45', 'Asla', 'عسلة', 'Asla'),
  ('45', 'Djenienne Bourezg', 'جنين بورزق', 'Moghrar'),
  ('45', 'El Biodh', 'البيوض', 'Mecheria'),
  ('45', 'Kasdir', 'القصدير', 'Mekmen Ben Amar'),
  ('45', 'Makmen Ben Amar', 'مكمن بن عمار', 'Mekmen Ben Amar'),
  ('45', 'Mecheria', 'المشرية', 'Mecheria'),
  ('45', 'Moghrar', 'مغرار', 'Moghrar'),
  ('45', 'Naama', 'النعامة', 'Naama'),
  ('45', 'Sfissifa', 'سفيسيفة', 'Sfissifa'),
  ('45', 'Tiout', 'تيوت', 'Ain Sefra')
on conflict (wilaya_code, name) do nothing;

-- 46 Aïn Témouchent
insert into public.communes (wilaya_code, name, name_ar, daira) values
  ('46', 'Aghlal', 'أغلال', 'Ain Kihel'),
  ('46', 'Ain El Arbaa', 'عين الأربعاء', 'Ain Larbaa'),
  ('46', 'Ain Kihal', 'عين الكيحل', 'Ain Kihel'),
  ('46', 'Ain Temouchent', 'عين تموشنت', 'Ain Temouchent'),
  ('46', 'Ain Tolba', 'عين الطلبة', 'Ain Kihel'),
  ('46', 'Aoubellil', 'عقب الليل', 'Ain Kihel'),
  ('46', 'Beni Saf', 'بني صاف', 'Beni Saf'),
  ('46', 'Bouzedjar', 'بوزجار', 'El Amria'),
  ('46', 'Chaabat El Ham', 'شعبة اللحم', 'El Maleh'),
  ('46', 'Chentouf', 'شنتوف', 'Hammam Bou Hadjar'),
  ('46', 'El Amria', 'العامرية', 'El Amria'),
  ('46', 'El Maleh', 'المالح', 'El Maleh'),
  ('46', 'El Messaid', 'المساعيد', 'El Amria'),
  ('46', 'Emir Abdelkader', 'الأمير عبد القادر', 'Beni Saf'),
  ('46', 'Hammam Bou Hadjar', 'حمام بوحجر', 'Hammam Bou Hadjar'),
  ('46', 'Hassasna', 'الحساسنة', 'Hammam Bou Hadjar'),
  ('46', 'Hassi El Ghella', 'حاسي الغلة', 'El Amria'),
  ('46', 'Oued Berkeche', 'وادي برقش', 'Hammam Bou Hadjar'),
  ('46', 'Oued Sebbah', 'وادي الصباح', 'Ain Larbaa'),
  ('46', 'Ouled Boudjemaa', 'أولاد بوجمعة', 'El Amria'),
  ('46', 'Ouled Kihal', 'أولاد الكيحل', 'El Maleh'),
  ('46', 'Oulhaca El Gheraba', 'ولهاصة الغرابة', 'Oulhassa Gheraba'),
  ('46', 'Sidi Ben Adda', 'سيدي بن عدة', 'Ain Temouchent'),
  ('46', 'Sidi Boumediene', 'سيدي بومدين', 'Ain Larbaa'),
  ('46', 'Sidi Ouriache', 'سيدي ورياش', 'Oulhassa Gheraba'),
  ('46', 'Sidi Safi', 'سيدي صافي', 'Beni Saf'),
  ('46', 'Tamzoura', 'تامزورة', 'Ain Larbaa'),
  ('46', 'Terga', 'تارقة', 'El Maleh')
on conflict (wilaya_code, name) do nothing;

-- 47 Ghardaïa
insert into public.communes (wilaya_code, name, name_ar, daira) values
  ('47', 'Berriane', 'بريان', 'Berriane'),
  ('47', 'Bounoura', 'بونورة', 'Bounoura'),
  ('47', 'Dhayet Bendhahoua', 'ضاية بن ضحوة', 'Dhayet Ben Dhahoua'),
  ('47', 'El Atteuf', 'العطف', 'Bounoura'),
  ('47', 'El Guerrara', 'القرارة', 'El Guerrara'),
  ('47', 'Ghardaia', 'غرداية', 'Ghardaia'),
  ('47', 'Mansoura', 'المنصورة', 'Mansourah'),
  ('47', 'Metlili', 'متليلي', 'Metlili'),
  ('47', 'Sebseb', 'سبسب', 'Metlili'),
  ('47', 'Zelfana', 'زلفانة', 'Zelfana')
on conflict (wilaya_code, name) do nothing;

-- 48 Relizane
insert into public.communes (wilaya_code, name, name_ar, daira) values
  ('48', 'Ain Rahma', 'عين الرحمة', 'Yellel'),
  ('48', 'Ain-Tarek', 'عين طارق', 'Ain Tarek'),
  ('48', 'Ammi Moussa', 'عمي موسى', 'Ammi Moussa'),
  ('48', 'Belaassel Bouzagza', 'بلعسل بوزقزة', 'El Matmar'),
  ('48', 'Bendaoud', 'بن داود', 'Relizane'),
  ('48', 'Beni Dergoun', 'بني درقن', 'Zemmoura'),
  ('48', 'Beni Zentis', 'بني زنطيس', 'Sidi M''hamed Ben Ali'),
  ('48', 'Dar Ben Abdelah', 'دار بن عبد الله', 'Zemmoura'),
  ('48', 'Djidiouia', 'جديوية', 'Djidiouia'),
  ('48', 'El H''madna', 'الحمادنة', 'El H''madna'),
  ('48', 'El Hassi', 'الحاسي', 'Ammi Moussa'),
  ('48', 'El Ouldja', 'الولجة', 'Ammi Moussa'),
  ('48', 'El-Guettar', 'القطار', 'Mazouna'),
  ('48', 'El-Matmar', 'المطمر', 'El Matmar'),
  ('48', 'Had Echkalla', 'حد الشكالة', 'Ain Tarek'),
  ('48', 'Hamri', 'حمري', 'Djidiouia'),
  ('48', 'Kalaa', 'القلعة', 'Yellel'),
  ('48', 'Lahlef', 'لحلاف', 'Oued Rhiou'),
  ('48', 'Mazouna', 'مازونة', 'Mazouna'),
  ('48', 'Mediouna', 'مديونة', 'Sidi M''hamed Ben Ali'),
  ('48', 'Mendes', 'منداس', 'Mendes'),
  ('48', 'Merdja Sidi Abed', 'مرجة سيدي عابد', 'Oued Rhiou'),
  ('48', 'Ouarizane', 'واريزان', 'Oued Rhiou'),
  ('48', 'Oued El Djemaa', 'وادي الجمعة', 'El H''madna'),
  ('48', 'Oued Essalem', 'وادي السلام', 'Mendes'),
  ('48', 'Oued-Rhiou', 'وادي رهيو', 'Oued Rhiou'),
  ('48', 'Ouled Aiche', 'أولاد يعيش', 'Ammi Moussa'),
  ('48', 'Ouled Sidi Mihoub', 'أولاد سيدي الميهوب', 'Djidiouia'),
  ('48', 'Ramka', 'الرمكة', 'Ramka'),
  ('48', 'Relizane', 'غليزان', 'Relizane'),
  ('48', 'Sidi Khettab', 'سيدي  خطاب', 'El Matmar'),
  ('48', 'Sidi Lazreg', 'سيدي لزرق', 'Mendes'),
  ('48', 'Sidi M''hamed Benali', 'سيدي أمحمد بن علي', 'Sidi M''hamed Ben Ali'),
  ('48', 'Sidi M''hamed Benaouda', 'سيدي امحمد بن عودة', 'El Matmar'),
  ('48', 'Sidi Saada', 'سيدي سعادة', 'Yellel'),
  ('48', 'Souk El Had', 'سوق الحد', 'Ramka'),
  ('48', 'Yellel', 'يلل', 'Yellel'),
  ('48', 'Zemmoura', 'زمورة', 'Zemmoura')
on conflict (wilaya_code, name) do nothing;

-- 49 Timimoun
insert into public.communes (wilaya_code, name, name_ar, daira) values
  ('49', 'Aougrout', 'أوقروت', 'Aougrout'),
  ('49', 'Charouine', 'شروين', 'Charouine'),
  ('49', 'Deldoul', 'دلدول', 'Aougrout'),
  ('49', 'Ksar Kaddour', 'قصر قدور', 'Tinerkouk'),
  ('49', 'Metarfa', 'المطارفة', 'Aougrout'),
  ('49', 'Ouled Aissa', 'أولاد عيسى', 'Charouine'),
  ('49', 'Ouled Said', 'أولاد السعيد', 'Timimoun'),
  ('49', 'Talmine', 'طالمين', 'Charouine'),
  ('49', 'Timimoun', 'تيميمون', 'Timimoun'),
  ('49', 'Tinerkouk', 'تنركوك', 'Tinerkouk')
on conflict (wilaya_code, name) do nothing;

-- 50 Bordj Badji Mokhtar
insert into public.communes (wilaya_code, name, name_ar, daira) values
  ('50', 'Bordj Badji Mokhtar', 'برج باجي مختار', 'Bordj Badji Mokhtar'),
  ('50', 'Timiaouine', 'تيمياوين', 'Bordj Badji Mokhtar')
on conflict (wilaya_code, name) do nothing;

-- 51 Ouled Djellal
insert into public.communes (wilaya_code, name, name_ar, daira) values
  ('51', 'Besbes', 'بسباس', 'Sidi Khaled'),
  ('51', 'Chaiba', 'الشعيبة', 'Ouled Djellal'),
  ('51', 'Doucen', 'الدوسن', 'Ouled Djellal'),
  ('51', 'Ouled Djellal', 'أولاد جلال', 'Ouled Djellal'),
  ('51', 'Ras El Miad', 'رأس الميعاد', 'Sidi Khaled'),
  ('51', 'Sidi Khaled', 'سيدي  خالد', 'Sidi Khaled')
on conflict (wilaya_code, name) do nothing;

-- 52 Béni Abbès
insert into public.communes (wilaya_code, name, name_ar, daira) values
  ('52', 'Beni-Abbes', 'بني عباس', 'Beni Abbes'),
  ('52', 'Beni-Ikhlef', 'بن يخلف', 'Kerzaz'),
  ('52', 'El Ouata', 'الواتة', 'El Ouata'),
  ('52', 'Igli', 'إقلي', 'Igli'),
  ('52', 'Kerzaz', 'كرزاز', 'Kerzaz'),
  ('52', 'Ksabi', 'القصابي', 'Ouled Khodeir'),
  ('52', 'Ouled-Khodeir', 'أولاد خضير', 'Ouled Khodeir'),
  ('52', 'Tamtert', 'تامترت', 'Beni Abbes'),
  ('52', 'Timoudi', 'تيمودي', 'Kerzaz')
on conflict (wilaya_code, name) do nothing;

-- 53 In Salah
insert into public.communes (wilaya_code, name, name_ar, daira) values
  ('53', 'Ain Salah', 'عين صالح', 'In Salah'),
  ('53', 'Foggaret Ezzoua', 'فقارة الزوى', 'In Salah'),
  ('53', 'Inghar', 'إينغر', 'In Ghar')
on conflict (wilaya_code, name) do nothing;

-- 54 In Guezzam
insert into public.communes (wilaya_code, name, name_ar, daira) values
  ('54', 'Ain Guezzam', 'عين قزام', 'In Guezzam'),
  ('54', 'Tin Zouatine', 'تين زواتين', 'Tin Zouatine')
on conflict (wilaya_code, name) do nothing;

-- 55 Touggourt
insert into public.communes (wilaya_code, name, name_ar, daira) values
  ('55', 'Benaceur', 'بن ناصر', 'Taibet'),
  ('55', 'Blidet Amor', 'بلدة اعمر', 'Temacine'),
  ('55', 'El Alia', 'العالية', 'El-Hadjira'),
  ('55', 'El-Hadjira', 'الحجيرة', 'El-Hadjira'),
  ('55', 'M''naguer', 'المنقر', 'Taibet'),
  ('55', 'Megarine', 'المقارين', 'Megarine'),
  ('55', 'Nezla', 'النزلة', 'Touggourt'),
  ('55', 'Sidi Slimane', 'سيدي سليمان', 'Megarine'),
  ('55', 'Taibet', 'الطيبات', 'Taibet'),
  ('55', 'Tebesbest', 'تبسبست', 'Touggourt'),
  ('55', 'Temacine', 'تماسين', 'Temacine'),
  ('55', 'Touggourt', 'تقرت', 'Touggourt'),
  ('55', 'Zaouia El Abidia', 'الزاوية العابدية', 'Touggourt')
on conflict (wilaya_code, name) do nothing;

-- 56 Djanet
insert into public.communes (wilaya_code, name, name_ar, daira) values
  ('56', 'Bordj El Haouass', 'برج الحواس', 'Djanet'),
  ('56', 'Djanet', 'جانت', 'Djanet')
on conflict (wilaya_code, name) do nothing;

-- 57 El Meghaier
insert into public.communes (wilaya_code, name, name_ar, daira) values
  ('57', 'Djamaa', 'جامعة', 'Djamaa'),
  ('57', 'El-M''ghaier', 'المغير', 'El Meghaier'),
  ('57', 'M''rara', 'المرارة', 'Djamaa'),
  ('57', 'Oum Touyour', 'أم الطيور', 'El Meghaier'),
  ('57', 'Sidi Amrane', 'سيدي عمران', 'Djamaa'),
  ('57', 'Sidi Khelil', 'سيدي خليل', 'El Meghaier'),
  ('57', 'Still', 'سطيل', 'El Meghaier'),
  ('57', 'Tenedla', 'تندلة', 'Djamaa')
on conflict (wilaya_code, name) do nothing;

-- 58 El Menia
insert into public.communes (wilaya_code, name, name_ar, daira) values
  ('58', 'El Meniaa', 'المنيعة', 'El Menia'),
  ('58', 'Hassi Fehal', 'حاسي الفحل', 'Mansourah'),
  ('58', 'Hassi Gara', 'حاسي القارة', 'El Menia')
on conflict (wilaya_code, name) do nothing;

